// AUTO-GENERATED by analysis/chaos_traits.py -- do not edit by hand.
// Speculative 'Chaos Board' traits (margin volatility + ceiling) over the last two
// completed seasons. NOT predictive; never feeds The Model or Value Finder.
export interface ChaosTrait { vol: number; ceiling: number; g: number; volPct: number; ceilPct: number }
export interface StadiumEnv { indoor: boolean; climate: string; surface: string }
export const CHAOS_WINDOW = ["2024", "2025"] as const;
export const NFL_CHAOS: Record<string, ChaosTrait> = {
"KC": {
"vol": 12.2,
"ceiling": 31,
"g": 37,
"volPct": 26.0,
"ceilPct": 45.0
},
"BAL": {
"vol": 14.7,
"ceiling": 31,
"g": 36,
"volPct": 74.0,
"ceilPct": 45.0
},
"PHI": {
"vol": 12.0,
"ceiling": 34,
"g": 39,
"volPct": 13.0,
"ceilPct": 65.0
},
"GB": {
"vol": 11.1,
"ceiling": 34,
"g": 36,
"volPct": 0.0,
"ceilPct": 65.0
},
"ATL": {
"vol": 13.4,
"ceiling": 27,
"g": 34,
"volPct": 52.0,
"ceilPct": 32.0
},
"PIT": {
"vol": 11.7,
"ceiling": 22,
"g": 36,
"volPct": 6.0,
"ceilPct": 10.0
},
"BUF": {
"vol": 13.2,
"ceiling": 37,
"g": 39,
"volPct": 45.0,
"ceilPct": 87.0
},
"ARI": {
"vol": 14.4,
"ceiling": 31,
"g": 34,
"volPct": 68.0,
"ceilPct": 45.0
},
"CHI": {
"vol": 12.6,
"ceiling": 28,
"g": 36,
"volPct": 32.0,
"ceilPct": 35.0
},
"TEN": {
"vol": 12.1,
"ceiling": 19,
"g": 34,
"volPct": 23.0,
"ceilPct": 3.0
},
"CIN": {
"vol": 13.8,
"ceiling": 24,
"g": 34,
"volPct": 58.0,
"ceilPct": 16.0
},
"NE": {
"vol": 14.6,
"ceiling": 32,
"g": 38,
"volPct": 71.0,
"ceilPct": 55.0
},
"IND": {
"vol": 12.3,
"ceiling": 34,
"g": 34,
"volPct": 29.0,
"ceilPct": 65.0
},
"HOU": {
"vol": 13.0,
"ceiling": 34,
"g": 38,
"volPct": 42.0,
"ceilPct": 65.0
},
"MIA": {
"vol": 14.8,
"ceiling": 24,
"g": 34,
"volPct": 81.0,
"ceilPct": 16.0
},
"JAX": {
"vol": 16.4,
"ceiling": 34,
"g": 35,
"volPct": 100.0,
"ceilPct": 65.0
},
"NO": {
"vol": 15.7,
"ceiling": 37,
"g": 34,
"volPct": 97.0,
"ceilPct": 87.0
},
"CAR": {
"vol": 14.8,
"ceiling": 30,
"g": 35,
"volPct": 81.0,
"ceilPct": 42.0
},
"NYG": {
"vol": 12.0,
"ceiling": 24,
"g": 34,
"volPct": 13.0,
"ceilPct": 16.0
},
"MIN": {
"vol": 15.0,
"ceiling": 38,
"g": 35,
"volPct": 87.0,
"ceilPct": 94.0
},
"LAC": {
"vol": 14.2,
"ceiling": 33,
"g": 36,
"volPct": 65.0,
"ceilPct": 58.0
},
"LV": {
"vol": 11.5,
"ceiling": 15,
"g": 34,
"volPct": 3.0,
"ceilPct": 0.0
},
"SEA": {
"vol": 13.2,
"ceiling": 35,
"g": 37,
"volPct": 45.0,
"ceilPct": 84.0
},
"DEN": {
"vol": 13.7,
"ceiling": 38,
"g": 37,
"volPct": 55.0,
"ceilPct": 94.0
},
"CLE": {
"vol": 12.0,
"ceiling": 25,
"g": 34,
"volPct": 13.0,
"ceilPct": 26.0
},
"DAL": {
"vol": 14.7,
"ceiling": 22,
"g": 34,
"volPct": 74.0,
"ceilPct": 10.0
},
"TB": {
"vol": 12.9,
"ceiling": 34,
"g": 35,
"volPct": 39.0,
"ceilPct": 65.0
},
"WAS": {
"vol": 15.5,
"ceiling": 33,
"g": 37,
"volPct": 94.0,
"ceilPct": 58.0
},
"DET": {
"vol": 15.2,
"ceiling": 46,
"g": 35,
"volPct": 90.0,
"ceilPct": 100.0
},
"LA": {
"vol": 11.9,
"ceiling": 28,
"g": 39,
"volPct": 10.0,
"ceilPct": 35.0
},
"SF": {
"vol": 14.1,
"ceiling": 25,
"g": 36,
"volPct": 61.0,
"ceilPct": 26.0
},
"NYJ": {
"vol": 12.8,
"ceiling": 21,
"g": 34,
"volPct": 35.0,
"ceilPct": 6.0
}
};
export const CFB_CHAOS: Record<string, ChaosTrait> = {
"Alabama": {
"vol": 23.5,
"ceiling": 73,
"g": 26,
"volPct": 98.0,
"ceilPct": 100.0
},
"Western Kentucky": {
"vol": 20.5,
"ceiling": 28,
"g": 25,
"volPct": 80.0,
"ceilPct": 23.0
},
"Florida": {
"vol": 17.3,
"ceiling": 28,
"g": 23,
"volPct": 38.0,
"ceilPct": 23.0
},
"Miami": {
"vol": 16.9,
"ceiling": 62,
"g": 27,
"volPct": 34.0,
"ceilPct": 96.0
},
"Georgia": {
"vol": 14.5,
"ceiling": 38,
"g": 26,
"volPct": 7.0,
"ceilPct": 56.0
},
"Clemson": {
"vol": 18.0,
"ceiling": 46,
"g": 25,
"volPct": 45.0,
"ceilPct": 79.0
},
"Kentucky": {
"vol": 21.1,
"ceiling": 35,
"g": 22,
"volPct": 84.0,
"ceilPct": 47.0
},
"Southern Miss": {
"vol": 19.4,
"ceiling": 28,
"g": 23,
"volPct": 64.0,
"ceilPct": 23.0
},
"Oklahoma": {
"vol": 20.0,
"ceiling": 48,
"g": 24,
"volPct": 76.0,
"ceilPct": 82.0
},
"Temple": {
"vol": 22.0,
"ceiling": 35,
"g": 23,
"volPct": 88.0,
"ceilPct": 47.0
},
"South Carolina": {
"vol": 19.4,
"ceiling": 44,
"g": 23,
"volPct": 64.0,
"ceilPct": 74.0
},
"Old Dominion": {
"vol": 18.9,
"ceiling": 40,
"g": 24,
"volPct": 59.0,
"ceilPct": 61.0
},
"Texas": {
"vol": 19.8,
"ceiling": 55,
"g": 29,
"volPct": 70.0,
"ceilPct": 89.0
},
"Colorado State": {
"vol": 18.8,
"ceiling": 28,
"g": 23,
"volPct": 58.0,
"ceilPct": 23.0
},
"Texas A&M": {
"vol": 14.3,
"ceiling": 35,
"g": 24,
"volPct": 5.0,
"ceilPct": 47.0
},
"Notre Dame": {
"vol": 18.4,
"ceiling": 63,
"g": 28,
"volPct": 50.0,
"ceilPct": 96.0
},
"Vanderbilt": {
"vol": 15.4,
"ceiling": 49,
"g": 24,
"volPct": 15.0,
"ceilPct": 84.0
},
"Virginia Tech": {
"vol": 14.8,
"ceiling": 24,
"g": 24,
"volPct": 10.0,
"ceilPct": 14.0
},
"LSU": {
"vol": 14.4,
"ceiling": 32,
"g": 24,
"volPct": 6.0,
"ceilPct": 36.0
},
"USC": {
"vol": 17.9,
"ceiling": 60,
"g": 26,
"volPct": 44.0,
"ceilPct": 94.0
},
"South Florida": {
"vol": 25.7,
"ceiling": 49,
"g": 24,
"volPct": 100.0,
"ceilPct": 84.0
},
"Oklahoma State": {
"vol": 20.3,
"ceiling": 35,
"g": 22,
"volPct": 78.0,
"ceilPct": 47.0
},
"Arkansas": {
"vol": 18.4,
"ceiling": 42,
"g": 23,
"volPct": 50.0,
"ceilPct": 68.0
},
"Auburn": {
"vol": 15.4,
"ceiling": 39,
"g": 22,
"volPct": 15.0,
"ceilPct": 59.0
},
"California": {
"vol": 15.9,
"ceiling": 37,
"g": 24,
"volPct": 24.0,
"ceilPct": 55.0
},
"Ole Miss": {
"vol": 17.2,
"ceiling": 56,
"g": 26,
"volPct": 37.0,
"ceilPct": 90.0
},
"Middle Tennessee": {
"vol": 15.4,
"ceiling": 14,
"g": 22,
"volPct": 15.0,
"ceilPct": 1.0
},
"Arizona State": {
"vol": 16.1,
"ceiling": 42,
"g": 26,
"volPct": 25.0,
"ceilPct": 68.0
},
"Mississippi State": {
"vol": 15.3,
"ceiling": 28,
"g": 23,
"volPct": 12.0,
"ceilPct": 23.0
},
"Missouri": {
"vol": 19.9,
"ceiling": 42,
"g": 24,
"volPct": 73.0,
"ceilPct": 68.0
},
"Buffalo": {
"vol": 20.1,
"ceiling": 36,
"g": 23,
"volPct": 77.0,
"ceilPct": 52.0
},
"Houston": {
"vol": 16.5,
"ceiling": 26,
"g": 24,
"volPct": 27.0,
"ceilPct": 19.0
},
"NC State": {
"vol": 17.7,
"ceiling": 31,
"g": 24,
"volPct": 43.0,
"ceilPct": 32.0
},
"Tennessee": {
"vol": 22.9,
"ceiling": 71,
"g": 24,
"volPct": 95.0,
"ceilPct": 99.0
},
"Michigan": {
"vol": 18.9,
"ceiling": 60,
"g": 26,
"volPct": 59.0,
"ceilPct": 94.0
},
"Wisconsin": {
"vol": 23.4,
"ceiling": 46,
"g": 23,
"volPct": 97.0,
"ceilPct": 79.0
},
"UAB": {
"vol": 20.3,
"ceiling": 38,
"g": 22,
"volPct": 78.0,
"ceilPct": 56.0
},
"New Mexico": {
"vol": 13.7,
"ceiling": 25,
"g": 23,
"volPct": 3.0,
"ceilPct": 16.0
},
"Wake Forest": {
"vol": 18.0,
"ceiling": 38,
"g": 23,
"volPct": 45.0,
"ceilPct": 56.0
},
"Toledo": {
"vol": 18.4,
"ceiling": 42,
"g": 24,
"volPct": 50.0,
"ceilPct": 68.0
},
"Boston College": {
"vol": 15.5,
"ceiling": 22,
"g": 23,
"volPct": 17.0,
"ceilPct": 13.0
},
"Tulane": {
"vol": 22.4,
"ceiling": 51,
"g": 27,
"volPct": 92.0,
"ceilPct": 87.0
},
"Kent State": {
"vol": 24.7,
"ceiling": 36,
"g": 22,
"volPct": 99.0,
"ceilPct": 52.0
},
"UTSA": {
"vol": 24.8,
"ceiling": 48,
"g": 24,
"volPct": 99.0,
"ceilPct": 82.0
},
"Georgia State": {
"vol": 14.4,
"ceiling": 8,
"g": 22,
"volPct": 6.0,
"ceilPct": 1.0
},
"Ohio": {
"vol": 18.4,
"ceiling": 41,
"g": 25,
"volPct": 50.0,
"ceilPct": 64.0
},
"UCLA": {
"vol": 17.3,
"ceiling": 25,
"g": 24,
"volPct": 38.0,
"ceilPct": 16.0
},
"Georgia Southern": {
"vol": 18.3,
"ceiling": 20,
"g": 24,
"volPct": 49.0,
"ceilPct": 9.0
},
"Akron": {
"vol": 22.9,
"ceiling": 34,
"g": 22,
"volPct": 95.0,
"ceilPct": 41.0
},
"UL Monroe": {
"vol": 22.0,
"ceiling": 26,
"g": 22,
"volPct": 88.0,
"ceilPct": 19.0
},
"Bowling Green": {
"vol": 15.3,
"ceiling": 31,
"g": 23,
"volPct": 12.0,
"ceilPct": 32.0
},
"South Alabama": {
"vol": 15.8,
"ceiling": 34,
"g": 23,
"volPct": 21.0,
"ceilPct": 41.0
},
"UCF": {
"vol": 20.0,
"ceiling": 44,
"g": 22,
"volPct": 76.0,
"ceilPct": 74.0
},
"Massachusetts": {
"vol": 13.1,
"ceiling": -1,
"g": 21,
"volPct": 1.0,
"ceilPct": 0.0
},
"Ball State": {
"vol": 19.8,
"ceiling": 14,
"g": 22,
"volPct": 70.0,
"ceilPct": 1.0
},
"New Mexico State": {
"vol": 18.1,
"ceiling": 27,
"g": 22,
"volPct": 47.0,
"ceilPct": 20.0
},
"Louisiana Tech": {
"vol": 18.5,
"ceiling": 41,
"g": 24,
"volPct": 55.0,
"ceilPct": 64.0
},
"UTEP": {
"vol": 15.8,
"ceiling": 18,
"g": 22,
"volPct": 21.0,
"ceilPct": 7.0
},
"Florida State": {
"vol": 21.5,
"ceiling": 56,
"g": 22,
"volPct": 87.0,
"ceilPct": 90.0
},
"Georgia Tech": {
"vol": 11.7,
"ceiling": 25,
"g": 24,
"volPct": 0.0,
"ceilPct": 16.0
},
"Louisville": {
"vol": 15.5,
"ceiling": 41,
"g": 24,
"volPct": 17.0,
"ceilPct": 64.0
},
"Minnesota": {
"vol": 17.0,
"ceiling": 27,
"g": 24,
"volPct": 35.0,
"ceilPct": 20.0
},
"North Carolina": {
"vol": 16.7,
"ceiling": 27,
"g": 23,
"volPct": 30.0,
"ceilPct": 20.0
},
"Indiana": {
"vol": 21.2,
"ceiling": 66,
"g": 27,
"volPct": 84.0,
"ceilPct": 97.0
},
"Florida International": {
"vol": 21.7,
"ceiling": 40,
"g": 23,
"volPct": 87.0,
"ceilPct": 61.0
},
"Maryland": {
"vol": 20.7,
"ceiling": 43,
"g": 22,
"volPct": 81.0,
"ceilPct": 73.0
},
"UConn": {
"vol": 18.1,
"ceiling": 44,
"g": 24,
"volPct": 47.0,
"ceilPct": 74.0
},
"Fresno State": {
"vol": 21.0,
"ceiling": 48,
"g": 24,
"volPct": 83.0,
"ceilPct": 82.0
},
"Michigan State": {
"vol": 14.9,
"ceiling": 17,
"g": 22,
"volPct": 10.0,
"ceilPct": 5.0
},
"Florida Atlantic": {
"vol": 21.2,
"ceiling": 47,
"g": 22,
"volPct": 84.0,
"ceilPct": 81.0
},
"Nebraska": {
"vol": 22.1,
"ceiling": 68,
"g": 24,
"volPct": 90.0,
"ceilPct": 99.0
},
"Ohio State": {
"vol": 15.8,
"ceiling": 56,
"g": 29,
"volPct": 21.0,
"ceilPct": 90.0
},
"West Virginia": {
"vol": 18.2,
"ceiling": 24,
"g": 23,
"volPct": 48.0,
"ceilPct": 14.0
},
"Penn State": {
"vol": 17.9,
"ceiling": 56,
"g": 28,
"volPct": 44.0,
"ceilPct": 90.0
},
"Hawai'i": {
"vol": 19.7,
"ceiling": 32,
"g": 22,
"volPct": 69.0,
"ceilPct": 36.0
},
"Western Michigan": {
"vol": 20.7,
"ceiling": 42,
"g": 25,
"volPct": 81.0,
"ceilPct": 68.0
},
"Illinois": {
"vol": 19.6,
"ceiling": 38,
"g": 24,
"volPct": 67.0,
"ceilPct": 56.0
},
"Kansas": {
"vol": 16.6,
"ceiling": 31,
"g": 22,
"volPct": 28.0,
"ceilPct": 32.0
},
"Iowa": {
"vol": 17.1,
"ceiling": 40,
"g": 24,
"volPct": 36.0,
"ceilPct": 61.0
},
"Iowa State": {
"vol": 14.6,
"ceiling": 45,
"g": 24,
"volPct": 8.0,
"ceilPct": 76.0
},
"Colorado": {
"vol": 22.5,
"ceiling": 52,
"g": 24,
"volPct": 93.0,
"ceilPct": 88.0
},
"Oregon": {
"vol": 19.7,
"ceiling": 66,
"g": 27,
"volPct": 69.0,
"ceilPct": 97.0
},
"Boise State": {
"vol": 18.5,
"ceiling": 33,
"g": 26,
"volPct": 55.0,
"ceilPct": 41.0
},
"Rutgers": {
"vol": 19.5,
"ceiling": 32,
"g": 23,
"volPct": 67.0,
"ceilPct": 36.0
},
"Utah State": {
"vol": 21.3,
"ceiling": 45,
"g": 23,
"volPct": 86.0,
"ceilPct": 76.0
},
"Washington": {
"vol": 19.6,
"ceiling": 36,
"g": 24,
"volPct": 67.0,
"ceilPct": 52.0
},
"Eastern Michigan": {
"vol": 13.4,
"ceiling": 19,
"g": 22,
"volPct": 2.0,
"ceilPct": 8.0
},
"Central Michigan": {
"vol": 20.6,
"ceiling": 25,
"g": 23,
"volPct": 81.0,
"ceilPct": 16.0
},
"Troy": {
"vol": 15.9,
"ceiling": 32,
"g": 24,
"volPct": 24.0,
"ceilPct": 36.0
},
"Virginia": {
"vol": 16.7,
"ceiling": 41,
"g": 24,
"volPct": 30.0,
"ceilPct": 64.0
},
"Arkansas State": {
"vol": 16.6,
"ceiling": 16,
"g": 24,
"volPct": 28.0,
"ceilPct": 4.0
},
"Nevada": {
"vol": 17.5,
"ceiling": 45,
"g": 23,
"volPct": 40.0,
"ceilPct": 76.0
},
"Oregon State": {
"vol": 16.1,
"ceiling": 21,
"g": 22,
"volPct": 25.0,
"ceilPct": 10.0
},
"Washington State": {
"vol": 19.2,
"ceiling": 32,
"g": 24,
"volPct": 63.0,
"ceilPct": 36.0
},
"Charlotte": {
"vol": 17.1,
"ceiling": 31,
"g": 22,
"volPct": 36.0,
"ceilPct": 32.0
},
"Northwestern": {
"vol": 19.0,
"ceiling": 35,
"g": 23,
"volPct": 61.0,
"ceilPct": 47.0
},
"Marshall": {
"vol": 17.3,
"ceiling": 34,
"g": 23,
"volPct": 38.0,
"ceilPct": 41.0
},
"Purdue": {
"vol": 22.1,
"ceiling": 31,
"g": 22,
"volPct": 90.0,
"ceilPct": 32.0
},
"Northern Illinois": {
"vol": 16.8,
"ceiling": 42,
"g": 23,
"volPct": 32.0,
"ceilPct": 68.0
},
"Miami (OH)": {
"vol": 18.4,
"ceiling": 39,
"g": 27,
"volPct": 50.0,
"ceilPct": 59.0
},
"Stanford": {
"vol": 16.4,
"ceiling": 21,
"g": 23,
"volPct": 27.0,
"ceilPct": 10.0
},
"Navy": {
"vol": 19.8,
"ceiling": 34,
"g": 24,
"volPct": 70.0,
"ceilPct": 41.0
},
"Duke": {
"vol": 15.5,
"ceiling": 35,
"g": 25,
"volPct": 17.0,
"ceilPct": 47.0
},
"Rice": {
"vol": 17.6,
"ceiling": 14,
"g": 23,
"volPct": 42.0,
"ceilPct": 1.0
},
"North Texas": {
"vol": 22.3,
"ceiling": 49,
"g": 25,
"volPct": 91.0,
"ceilPct": 84.0
},
"Army": {
"vol": 17.5,
"ceiling": 42,
"g": 25,
"volPct": 40.0,
"ceilPct": 68.0
},
"Liberty": {
"vol": 12.6,
"ceiling": 29,
"g": 22,
"volPct": 1.0,
"ceilPct": 30.0
},
"TCU": {
"vol": 15.3,
"ceiling": 34,
"g": 24,
"volPct": 12.0,
"ceilPct": 41.0
},
"Syracuse": {
"vol": 19.3,
"ceiling": 17,
"g": 23,
"volPct": 64.0,
"ceilPct": 5.0
},
"Pittsburgh": {
"vol": 18.6,
"ceiling": 41,
"g": 24,
"volPct": 57.0,
"ceilPct": 64.0
},
"SMU": {
"vol": 15.3,
"ceiling": 32,
"g": 25,
"volPct": 12.0,
"ceilPct": 36.0
},
"BYU": {
"vol": 13.8,
"ceiling": 31,
"g": 25,
"volPct": 4.0,
"ceilPct": 32.0
},
"UNLV": {
"vol": 15.7,
"ceiling": 45,
"g": 26,
"volPct": 21.0,
"ceilPct": 76.0
},
"App State": {
"vol": 18.9,
"ceiling": 23,
"g": 22,
"volPct": 59.0,
"ceilPct": 13.0
},
"Jacksonville State": {
"vol": 18.3,
"ceiling": 41,
"g": 27,
"volPct": 49.0,
"ceilPct": 64.0
},
"Cincinnati": {
"vol": 16.8,
"ceiling": 34,
"g": 23,
"volPct": 32.0,
"ceilPct": 41.0
},
"San Diego State": {
"vol": 19.4,
"ceiling": 34,
"g": 23,
"volPct": 64.0,
"ceilPct": 41.0
},
"Memphis": {
"vol": 15.5,
"ceiling": 38,
"g": 24,
"volPct": 17.0,
"ceilPct": 56.0
},
"James Madison": {
"vol": 19.9,
"ceiling": 56,
"g": 25,
"volPct": 73.0,
"ceilPct": 90.0
},
"Coastal Carolina": {
"vol": 23.3,
"ceiling": 28,
"g": 24,
"volPct": 96.0,
"ceilPct": 23.0
},
"San Jos\u00e9 State": {
"vol": 15.5,
"ceiling": 21,
"g": 23,
"volPct": 17.0,
"ceilPct": 10.0
},
"Louisiana": {
"vol": 16.7,
"ceiling": 36,
"g": 25,
"volPct": 30.0,
"ceilPct": 52.0
},
"Arizona": {
"vol": 22.8,
"ceiling": 35,
"g": 23,
"volPct": 94.0,
"ceilPct": 47.0
},
"Wyoming": {
"vol": 15.1,
"ceiling": 28,
"g": 22,
"volPct": 11.0,
"ceilPct": 23.0
},
"Kansas State": {
"vol": 14.7,
"ceiling": 27,
"g": 23,
"volPct": 9.0,
"ceilPct": 20.0
},
"Sam Houston": {
"vol": 19.9,
"ceiling": 20,
"g": 25,
"volPct": 73.0,
"ceilPct": 9.0
},
"Utah": {
"vol": 18.9,
"ceiling": 46,
"g": 23,
"volPct": 59.0,
"ceilPct": 79.0
},
"Baylor": {
"vol": 16.8,
"ceiling": 28,
"g": 23,
"volPct": 32.0,
"ceilPct": 23.0
},
"Texas Tech": {
"vol": 22.6,
"ceiling": 49,
"g": 25,
"volPct": 93.0,
"ceilPct": 84.0
},
"Air Force": {
"vol": 14.0,
"ceiling": 28,
"g": 22,
"volPct": 4.0,
"ceilPct": 23.0
},
"Texas State": {
"vol": 19.8,
"ceiling": 55,
"g": 24,
"volPct": 70.0,
"ceilPct": 89.0
},
"Tulsa": {
"vol": 17.5,
"ceiling": 17,
"g": 22,
"volPct": 40.0,
"ceilPct": 5.0
},
"Kennesaw State": {
"vol": 18.5,
"ceiling": 28,
"g": 24,
"volPct": 55.0,
"ceilPct": 23.0
},
"East Carolina": {
"vol": 20.3,
"ceiling": 39,
"g": 24,
"volPct": 78.0,
"ceilPct": 59.0
},
"Missouri State": {
"vol": 18.4,
"ceiling": 14,
"g": 12,
"volPct": 50.0,
"ceilPct": 1.0
},
"Delaware": {
"vol": 19.0,
"ceiling": 30,
"g": 12,
"volPct": 61.0,
"ceilPct": 31.0
}
};
export const NFL_ENV: Record<string, StadiumEnv> = {
"ARI": {
"indoor": true,
"climate": "controlled",
"surface": "grass"
},
"ATL": {
"indoor": true,
"climate": "controlled",
"surface": "turf"
},
"BAL": {
"indoor": false,
"climate": "mild",
"surface": "grass"
},
"BUF": {
"indoor": false,
"climate": "cold",
"surface": "turf"
},
"CAR": {
"indoor": false,
"climate": "mild",
"surface": "grass"
},
"CHI": {
"indoor": false,
"climate": "cold",
"surface": "grass"
},
"CIN": {
"indoor": false,
"climate": "mild",
"surface": "turf"
},
"CLE": {
"indoor": false,
"climate": "cold",
"surface": "grass"
},
"DAL": {
"indoor": true,
"climate": "controlled",
"surface": "turf"
},
"DEN": {
"indoor": false,
"climate": "mild",
"surface": "grass"
},
"DET": {
"indoor": true,
"climate": "controlled",
"surface": "turf"
},
"GB": {
"indoor": false,
"climate": "cold",
"surface": "grass"
},
"HOU": {
"indoor": true,
"climate": "controlled",
"surface": "turf"
},
"IND": {
"indoor": true,
"climate": "controlled",
"surface": "turf"
},
"JAX": {
"indoor": false,
"climate": "warm",
"surface": "grass"
},
"KC": {
"indoor": false,
"climate": "mild",
"surface": "grass"
},
"LA": {
"indoor": true,
"climate": "controlled",
"surface": "turf"
},
"LAC": {
"indoor": true,
"climate": "controlled",
"surface": "turf"
},
"LV": {
"indoor": true,
"climate": "controlled",
"surface": "grass"
},
"MIA": {
"indoor": false,
"climate": "warm",
"surface": "grass"
},
"MIN": {
"indoor": true,
"climate": "controlled",
"surface": "turf"
},
"NE": {
"indoor": false,
"climate": "cold",
"surface": "turf"
},
"NO": {
"indoor": true,
"climate": "controlled",
"surface": "turf"
},
"NYG": {
"indoor": false,
"climate": "cold",
"surface": "turf"
},
"NYJ": {
"indoor": false,
"climate": "mild",
"surface": "turf"
},
"PHI": {
"indoor": false,
"climate": "cold",
"surface": "grass"
},
"PIT": {
"indoor": false,
"climate": "cold",
"surface": "grass"
},
"SEA": {
"indoor": false,
"climate": "cold",
"surface": "turf"
},
"SF": {
"indoor": false,
"climate": "mild",
"surface": "grass"
},
"TB": {
"indoor": false,
"climate": "warm",
"surface": "grass"
},
"TEN": {
"indoor": false,
"climate": "mild",
"surface": "grass"
},
"WAS": {
"indoor": false,
"climate": "mild",
"surface": "grass"
}
};
