// AUTO-GENERATED by analysis/coach_tendencies.py — do not edit by hand.
// Head-coach CONTEXT (not an edge), keyed by each team's current coach.
// Shown now: production — offensive yards/game + points/game, career (2021-24, the
// span of our play-by-play) and the prior season (2024). null = under a half-season
// of games with us. Aggressiveness (gray-zone 4th-down go rate) + pass tendency (PROE)
// are also carried for later use; `rated:false` = new coach / not enough history yet.
export interface CoachTendency {
  team: string; coach: string; rated: boolean;
  ydsCareer?: number | null; ydsPrior?: number | null;
  ptsCareer?: number | null; ptsPrior?: number | null;
  gCareer?: number | null; gPrior?: number | null;
  goRate?: number; goRateLg?: number; aggPct?: number; aggLabel?: string; fourthN?: number;
  proe?: number | null; proeLabel?: string | null;
}
export const LEAGUE_GO_RATE = 54.5;
export const COACH_TENDENCIES: Record<string, CoachTendency> = {
  "ARI": {"team": "ARI", "coach": "Jonathan Gannon", "ydsCareer": 342.0, "ydsPrior": 359.0, "ptsCareer": 21.5, "ptsPrior": 23.5, "gCareer": 34, "gPrior": 17, "rated": true, "goRate": 50.0, "goRateLg": 54.5, "aggPct": 33, "aggLabel": "Cautious", "fourthN": 16, "proe": -2.614, "proeLabel": "Run-leaning"},
  "ATL": {"team": "ATL", "coach": "Raheem Morris", "ydsCareer": 371.0, "ydsPrior": 371.0, "ptsCareer": 22.9, "ptsPrior": 22.9, "gCareer": 17, "gPrior": 17, "rated": false},
  "BAL": {"team": "BAL", "coach": "Jesse Minter", "ydsCareer": null, "ydsPrior": null, "ptsCareer": null, "ptsPrior": null, "gCareer": null, "gPrior": null, "rated": false},
  "BUF": {"team": "BUF", "coach": "Sean McDermott", "ydsCareer": 381.0, "ydsPrior": 363.0, "ptsCareer": 28.7, "ptsPrior": 30.6, "gCareer": 76, "gPrior": 20, "rated": true, "goRate": 55.6, "goRateLg": 54.5, "aggPct": 50, "aggLabel": "Balanced", "fourthN": 45, "proe": 3.25, "proeLabel": "Pass-heavy"},
  "CAR": {"team": "CAR", "coach": "Dave Canales", "ydsCareer": 299.0, "ydsPrior": 299.0, "ptsCareer": 20.1, "ptsPrior": 20.1, "gCareer": 17, "gPrior": 17, "rated": false},
  "CHI": {"team": "CHI", "coach": "Ben Johnson", "ydsCareer": null, "ydsPrior": null, "ptsCareer": null, "ptsPrior": null, "gCareer": null, "gPrior": null, "rated": false},
  "CIN": {"team": "CIN", "coach": "Zac Taylor", "ydsCareer": 350.0, "ydsPrior": 366.0, "ptsCareer": 25.4, "ptsPrior": 27.8, "gCareer": 74, "gPrior": 17, "rated": true, "goRate": 45.5, "goRateLg": 54.5, "aggPct": 29, "aggLabel": "Cautious", "fourthN": 44, "proe": 7.628, "proeLabel": "Pass-heavy"},
  "CLE": {"team": "CLE", "coach": "Todd Monken", "ydsCareer": null, "ydsPrior": null, "ptsCareer": null, "ptsPrior": null, "gCareer": null, "gPrior": null, "rated": false},
  "DAL": {"team": "DAL", "coach": "Brian Schottenheimer", "ydsCareer": null, "ydsPrior": null, "ptsCareer": null, "ptsPrior": null, "gCareer": null, "gPrior": null, "rated": false},
  "DEN": {"team": "DEN", "coach": "Sean Payton", "ydsCareer": 309.0, "ydsPrior": 320.0, "ptsCareer": 22.2, "ptsPrior": 24.0, "gCareer": 52, "gPrior": 18, "rated": true, "goRate": 70.8, "goRateLg": 54.5, "aggPct": 98, "aggLabel": "Very aggressive", "fourthN": 24, "proe": -1.616, "proeLabel": "Run-leaning"},
  "DET": {"team": "DET", "coach": "Dan Campbell", "ydsCareer": 380.0, "ydsPrior": 417.0, "ptsCareer": 26.7, "ptsPrior": 33.1, "gCareer": 72, "gPrior": 18, "rated": true, "goRate": 68.6, "goRateLg": 54.5, "aggPct": 90, "aggLabel": "Very aggressive", "fourthN": 51, "proe": -3.95, "proeLabel": "Run-heavy"},
  "GB": {"team": "GB", "coach": "Matt LaFleur", "ydsCareer": 355.0, "ydsPrior": 368.0, "ptsCareer": 24.3, "ptsPrior": 26.1, "gCareer": 72, "gPrior": 18, "rated": true, "goRate": 68.6, "goRateLg": 54.5, "aggPct": 88, "aggLabel": "Very aggressive", "fourthN": 35, "proe": -3.12, "proeLabel": "Run-heavy"},
  "HOU": {"team": "HOU", "coach": "DeMeco Ryans", "ydsCareer": 331.0, "ydsPrior": 325.0, "ptsCareer": 22.4, "ptsPrior": 22.0, "gCareer": 38, "gPrior": 19, "rated": true, "goRate": 30.0, "goRateLg": 54.5, "aggPct": 7, "aggLabel": "Conservative", "fourthN": 20, "proe": -2.162, "proeLabel": "Run-leaning"},
  "IND": {"team": "IND", "coach": "Shane Steichen", "ydsCareer": 337.0, "ydsPrior": 336.0, "ptsCareer": 22.7, "ptsPrior": 22.2, "gCareer": 34, "gPrior": 17, "rated": true, "goRate": 66.7, "goRateLg": 54.5, "aggPct": 80, "aggLabel": "Aggressive", "fourthN": 24, "proe": -4.996, "proeLabel": "Run-heavy"},
  "JAX": {"team": "JAX", "coach": "Liam Coen", "ydsCareer": null, "ydsPrior": null, "ptsCareer": null, "ptsPrior": null, "gCareer": null, "gPrior": null, "rated": false},
  "KC": {"team": "KC", "coach": "Andy Reid", "ydsCareer": 374.0, "ydsPrior": 324.0, "ptsCareer": 25.9, "ptsPrior": 23.1, "gCareer": 81, "gPrior": 20, "rated": true, "goRate": 58.5, "goRateLg": 54.5, "aggPct": 66, "aggLabel": "Aggressive", "fourthN": 41, "proe": 9.311, "proeLabel": "Pass-heavy"},
  "LA": {"team": "LA", "coach": "Sean McVay", "ydsCareer": 341.0, "ydsPrior": 334.0, "ptsCareer": 22.9, "ptsPrior": 21.9, "gCareer": 75, "gPrior": 19, "rated": true, "goRate": 54.3, "goRateLg": 54.5, "aggPct": 41, "aggLabel": "Balanced", "fourthN": 46, "proe": 0.906, "proeLabel": "Balanced"},
  "LAC": {"team": "LAC", "coach": "Jim Harbaugh", "ydsCareer": 323.0, "ydsPrior": 323.0, "ptsCareer": 23.0, "ptsPrior": 23.0, "gCareer": 18, "gPrior": 18, "rated": false},
  "LV": {"team": "LV", "coach": "Klint Kubliak", "ydsCareer": null, "ydsPrior": null, "ptsCareer": null, "ptsPrior": null, "gCareer": null, "gPrior": null, "rated": false},
  "MIA": {"team": "MIA", "coach": "Jeff Hafley", "ydsCareer": null, "ydsPrior": null, "ptsCareer": null, "ptsPrior": null, "gCareer": null, "gPrior": null, "rated": false},
  "MIN": {"team": "MIN", "coach": "Kevin O'Connell", "ydsCareer": 351.0, "ydsPrior": 344.0, "ptsCareer": 23.3, "ptsPrior": 24.5, "gCareer": 53, "gPrior": 18, "rated": true, "goRate": 57.1, "goRateLg": 54.5, "aggPct": 55, "aggLabel": "Balanced", "fourthN": 35, "proe": 3.263, "proeLabel": "Pass-heavy"},
  "NE": {"team": "NE", "coach": "Mike Vrabel", "ydsCareer": 311.0, "ydsPrior": null, "ptsCareer": 20.0, "ptsPrior": null, "gCareer": 52, "gPrior": null, "rated": true, "goRate": 57.6, "goRateLg": 54.5, "aggPct": 59, "aggLabel": "Balanced", "fourthN": 33, "proe": -8.405, "proeLabel": "Run-heavy"},
  "NO": {"team": "NO", "coach": "Kellen Moore", "ydsCareer": null, "ydsPrior": null, "ptsCareer": null, "ptsPrior": null, "gCareer": null, "gPrior": null, "rated": false},
  "NYG": {"team": "NYG", "coach": "John Harbaugh", "ydsCareer": 379.0, "ydsPrior": 426.0, "ptsCareer": 25.4, "ptsPrior": 30.1, "gCareer": 73, "gPrior": 19, "rated": true, "goRate": 55.6, "goRateLg": 54.5, "aggPct": 50, "aggLabel": "Balanced", "fourthN": 45, "proe": -0.82, "proeLabel": "Balanced"},
  "NYJ": {"team": "NYJ", "coach": "Aaron Glenn", "ydsCareer": null, "ydsPrior": null, "ptsCareer": null, "ptsPrior": null, "gCareer": null, "gPrior": null, "rated": false},
  "OAK": {"team": "OAK", "coach": "Jon Gruden", "ydsCareer": null, "ydsPrior": null, "ptsCareer": null, "ptsPrior": null, "gCareer": 5, "gPrior": null, "rated": false},
  "PHI": {"team": "PHI", "coach": "Nick Sirianni", "ydsCareer": 367.0, "ydsPrior": 368.0, "ptsCareer": 27.1, "ptsPrior": 29.0, "gCareer": 77, "gPrior": 21, "rated": true, "goRate": 71.8, "goRateLg": 54.5, "aggPct": 100, "aggLabel": "Very aggressive", "fourthN": 39, "proe": -1.006, "proeLabel": "Run-leaning"},
  "PIT": {"team": "PIT", "coach": "Mike McCarthy", "ydsCareer": 367.0, "ydsPrior": 328.0, "ptsCareer": 27.1, "ptsPrior": 20.6, "gCareer": 72, "gPrior": 17, "rated": true, "goRate": 70.7, "goRateLg": 54.5, "aggPct": 95, "aggLabel": "Very aggressive", "fourthN": 41, "proe": 0.042, "proeLabel": "Balanced"},
  "SD": {"team": "SD", "coach": "Mike McCoy", "ydsCareer": null, "ydsPrior": null, "ptsCareer": null, "ptsPrior": null, "gCareer": null, "gPrior": null, "rated": false},
  "SEA": {"team": "SEA", "coach": "Mike Macdonald", "ydsCareer": 333.0, "ydsPrior": 333.0, "ptsCareer": 22.1, "ptsPrior": 22.1, "gCareer": 17, "gPrior": 17, "rated": true, "goRate": 58.3, "goRateLg": 54.5, "aggPct": 62, "aggLabel": "Aggressive", "fourthN": 12, "proe": 2.156, "proeLabel": "Pass-leaning"},
  "SF": {"team": "SF", "coach": "Kyle Shanahan", "ydsCareer": 374.0, "ydsPrior": 377.0, "ptsCareer": 25.4, "ptsPrior": 22.9, "gCareer": 77, "gPrior": 17, "rated": true, "goRate": 41.2, "goRateLg": 54.5, "aggPct": 22, "aggLabel": "Cautious", "fourthN": 34, "proe": -3.193, "proeLabel": "Run-heavy"},
  "STL": {"team": "STL", "coach": "Jeff Fisher", "ydsCareer": null, "ydsPrior": null, "ptsCareer": null, "ptsPrior": null, "gCareer": null, "gPrior": null, "rated": false},
  "TB": {"team": "TB", "coach": "Todd Bowles", "ydsCareer": 356.0, "ydsPrior": 394.0, "ptsCareer": 22.8, "ptsPrior": 29.0, "gCareer": 55, "gPrior": 18, "rated": true, "goRate": 52.9, "goRateLg": 54.5, "aggPct": 39, "aggLabel": "Cautious", "fourthN": 34, "proe": 0.438, "proeLabel": "Balanced"},
  "TEN": {"team": "TEN", "coach": "Robert Saleh", "ydsCareer": 302.0, "ydsPrior": 311.0, "ptsCareer": 17.8, "ptsPrior": 19.9, "gCareer": 68, "gPrior": 17, "rated": true, "goRate": 37.0, "goRateLg": 54.5, "aggPct": 10, "aggLabel": "Conservative", "fourthN": 46, "proe": -1.574, "proeLabel": "Run-leaning"},
  "WAS": {"team": "WAS", "coach": "Dan Quinn", "ydsCareer": 375.0, "ydsPrior": 375.0, "ptsCareer": 28.8, "ptsPrior": 28.8, "gCareer": 20, "gPrior": 20, "rated": false},
};
