// AUTO-GENERATED by analysis/coach_tendencies.py — do not edit by hand.
// Head-coach CONTEXT (not an edge): 4th-down aggressiveness (gray-zone go rate vs
// the league) + pass tendency (PROE), from 2021-2024 play-by-play, keyed by each
// team's current coach. `rated:false` = new coach / not enough history yet.
export interface CoachTendency {
  team: string; coach: string; rated: boolean;
  goRate?: number; goRateLg?: number; aggPct?: number; aggLabel?: string; fourthN?: number;
  proe?: number | null; proeLabel?: string | null;
}
export const LEAGUE_GO_RATE = 54.5;
export const COACH_TENDENCIES: Record<string, CoachTendency> = {
  "ARI": {"team": "ARI", "coach": "Jonathan Gannon", "rated": true, "goRate": 50.0, "goRateLg": 54.5, "aggPct": 33, "aggLabel": "Cautious", "fourthN": 16, "proe": -2.614, "proeLabel": "Run-leaning"},
  "ATL": {"team": "ATL", "coach": "Raheem Morris", "rated": false},
  "BAL": {"team": "BAL", "coach": "Jesse Minter", "rated": false},
  "BUF": {"team": "BUF", "coach": "Sean McDermott", "rated": true, "goRate": 55.6, "goRateLg": 54.5, "aggPct": 50, "aggLabel": "Balanced", "fourthN": 45, "proe": 3.25, "proeLabel": "Pass-heavy"},
  "CAR": {"team": "CAR", "coach": "Dave Canales", "rated": false},
  "CHI": {"team": "CHI", "coach": "Ben Johnson", "rated": false},
  "CIN": {"team": "CIN", "coach": "Zac Taylor", "rated": true, "goRate": 45.5, "goRateLg": 54.5, "aggPct": 29, "aggLabel": "Cautious", "fourthN": 44, "proe": 7.628, "proeLabel": "Pass-heavy"},
  "CLE": {"team": "CLE", "coach": "Todd Monken", "rated": false},
  "DAL": {"team": "DAL", "coach": "Brian Schottenheimer", "rated": false},
  "DEN": {"team": "DEN", "coach": "Sean Payton", "rated": true, "goRate": 70.8, "goRateLg": 54.5, "aggPct": 98, "aggLabel": "Very aggressive", "fourthN": 24, "proe": -1.616, "proeLabel": "Run-leaning"},
  "DET": {"team": "DET", "coach": "Dan Campbell", "rated": true, "goRate": 68.6, "goRateLg": 54.5, "aggPct": 90, "aggLabel": "Very aggressive", "fourthN": 51, "proe": -3.95, "proeLabel": "Run-heavy"},
  "GB": {"team": "GB", "coach": "Matt LaFleur", "rated": true, "goRate": 68.6, "goRateLg": 54.5, "aggPct": 88, "aggLabel": "Very aggressive", "fourthN": 35, "proe": -3.12, "proeLabel": "Run-heavy"},
  "HOU": {"team": "HOU", "coach": "DeMeco Ryans", "rated": true, "goRate": 30.0, "goRateLg": 54.5, "aggPct": 7, "aggLabel": "Conservative", "fourthN": 20, "proe": -2.162, "proeLabel": "Run-leaning"},
  "IND": {"team": "IND", "coach": "Shane Steichen", "rated": true, "goRate": 66.7, "goRateLg": 54.5, "aggPct": 80, "aggLabel": "Aggressive", "fourthN": 24, "proe": -4.996, "proeLabel": "Run-heavy"},
  "JAX": {"team": "JAX", "coach": "Liam Coen", "rated": false},
  "KC": {"team": "KC", "coach": "Andy Reid", "rated": true, "goRate": 58.5, "goRateLg": 54.5, "aggPct": 66, "aggLabel": "Aggressive", "fourthN": 41, "proe": 9.311, "proeLabel": "Pass-heavy"},
  "LA": {"team": "LA", "coach": "Sean McVay", "rated": true, "goRate": 54.3, "goRateLg": 54.5, "aggPct": 41, "aggLabel": "Balanced", "fourthN": 46, "proe": 0.906, "proeLabel": "Balanced"},
  "LAC": {"team": "LAC", "coach": "Jim Harbaugh", "rated": false},
  "LV": {"team": "LV", "coach": "Klint Kubliak", "rated": false},
  "MIA": {"team": "MIA", "coach": "Jeff Hafley", "rated": false},
  "MIN": {"team": "MIN", "coach": "Kevin O'Connell", "rated": true, "goRate": 57.1, "goRateLg": 54.5, "aggPct": 55, "aggLabel": "Balanced", "fourthN": 35, "proe": 3.263, "proeLabel": "Pass-heavy"},
  "NE": {"team": "NE", "coach": "Mike Vrabel", "rated": true, "goRate": 57.6, "goRateLg": 54.5, "aggPct": 59, "aggLabel": "Balanced", "fourthN": 33, "proe": -8.405, "proeLabel": "Run-heavy"},
  "NO": {"team": "NO", "coach": "Kellen Moore", "rated": false},
  "NYG": {"team": "NYG", "coach": "John Harbaugh", "rated": true, "goRate": 55.6, "goRateLg": 54.5, "aggPct": 50, "aggLabel": "Balanced", "fourthN": 45, "proe": -0.82, "proeLabel": "Balanced"},
  "NYJ": {"team": "NYJ", "coach": "Aaron Glenn", "rated": false},
  "OAK": {"team": "OAK", "coach": "Jon Gruden", "rated": false},
  "PHI": {"team": "PHI", "coach": "Nick Sirianni", "rated": true, "goRate": 71.8, "goRateLg": 54.5, "aggPct": 100, "aggLabel": "Very aggressive", "fourthN": 39, "proe": -1.006, "proeLabel": "Run-leaning"},
  "PIT": {"team": "PIT", "coach": "Mike McCarthy", "rated": true, "goRate": 70.7, "goRateLg": 54.5, "aggPct": 95, "aggLabel": "Very aggressive", "fourthN": 41, "proe": 0.042, "proeLabel": "Balanced"},
  "SD": {"team": "SD", "coach": "Mike McCoy", "rated": false},
  "SEA": {"team": "SEA", "coach": "Mike Macdonald", "rated": true, "goRate": 58.3, "goRateLg": 54.5, "aggPct": 62, "aggLabel": "Aggressive", "fourthN": 12, "proe": 2.156, "proeLabel": "Pass-leaning"},
  "SF": {"team": "SF", "coach": "Kyle Shanahan", "rated": true, "goRate": 41.2, "goRateLg": 54.5, "aggPct": 22, "aggLabel": "Cautious", "fourthN": 34, "proe": -3.193, "proeLabel": "Run-heavy"},
  "STL": {"team": "STL", "coach": "Jeff Fisher", "rated": false},
  "TB": {"team": "TB", "coach": "Todd Bowles", "rated": true, "goRate": 52.9, "goRateLg": 54.5, "aggPct": 39, "aggLabel": "Cautious", "fourthN": 34, "proe": 0.438, "proeLabel": "Balanced"},
  "TEN": {"team": "TEN", "coach": "Robert Saleh", "rated": true, "goRate": 37.0, "goRateLg": 54.5, "aggPct": 10, "aggLabel": "Conservative", "fourthN": 46, "proe": -1.574, "proeLabel": "Run-leaning"},
  "WAS": {"team": "WAS", "coach": "Dan Quinn", "rated": false},
};
