// AUTO-GENERATED by analysis/contention.py — do not edit by hand.
// Each team's playoff picture (CONTEXT, not an edge) through the latest completed
// week. Empty before Week 10 / in the preseason — the flag stays hidden until then.
export interface Contention {
  team: string; record: string; seed: number; conf: string;
  status: string;   // Clinched | In a playoff spot | On the bubble | Long shot | Eliminated
  note: string;
}
export const CONTENTION_SEASON = 2026;
export const CONTENTION_THROUGH_WEEK = 0;
export const CONTENTION: Record<string, Contention> = {
  };
