// AUTO-GENERATED by analysis/incentive_export.py — do not edit by hand.
// Players CLOSE to a contract incentive (hand-curated list x live season stats).
// Shown on Special Considerations cards as live context; empty until players near one.
export interface IncentiveWatch { player: string; team: string; stat: string;
  label: string; current: number; threshold: number; remaining: number; pct: number }
export const INCENTIVE_SEASON = 2026;
export const INCENTIVE_WATCH: IncentiveWatch[] = [
];
