// AUTO-GENERATED by analysis/incentive_scrape.py — do not edit by hand.
// Over The Cap weekly Incentives Watch — players within practical reach of a
// contract incentive. Shown on Special Considerations cards. Empty in the preseason.
export interface IncentiveWatch { player: string; team: string; amount: string;
  requirement: string; currently: string; needed: string; pct: number | null }
export const INCENTIVE_SEASON = 2026;
export const INCENTIVE_WEEK = 0;
export const INCENTIVE_WATCH: IncentiveWatch[] = [
];
