// AUTO-GENERATED by mlb_game_model.py -- do not edit by hand.
// Projected runs. Held-out MAE 3.5175 vs 3.4668 for the league mean total (-1.5%).
// Team quality alone was worth 0.0%; the starting pitcher and the park move it.
// Generated 2026-10-08T20:31:06+00:00
export type MlbGame = { gameKey: string; game: string; commence: string;
  eventDate: string; home: string; away: string;
  homeAbbr: string; awayAbbr: string; homeSpName: string | null;
  awaySpName: string | null; homeSpFactor: number; awaySpFactor: number;
  homeRuns: number; awayRuns: number; total: number };

export const MLB_GAMES: MlbGame[] = [{"gameKey": "849832", "game": "Cleveland Guardians @ Chicago White Sox", "commence": "2026-10-09T00:00:00Z", "eventDate": "2026-10-09", "home": "Chicago White Sox", "away": "Cleveland Guardians", "homeAbbr": "CWS", "awayAbbr": "CLE", "homeSpName": "Hagen Smith", "awaySpName": "Parker Messick", "homeRuns": 3.25, "awayRuns": 4.33, "total": 7.59, "homeSpFactor": 1.0, "awaySpFactor": 0.742}, {"gameKey": "849831", "game": "Chicago White Sox @ Cleveland Guardians", "commence": "2026-10-11T00:00:00Z", "eventDate": "2026-10-11", "home": "Cleveland Guardians", "away": "Chicago White Sox", "homeAbbr": "CLE", "awayAbbr": "CWS", "homeSpName": null, "awaySpName": null, "homeRuns": 4.17, "awayRuns": 4.22, "total": 8.39, "homeSpFactor": 1.0, "awaySpFactor": 1.0}];
export const MLB_GAME_SCORES = {"model": 3.5152, "base": 3.5637, "gain": 1.4, "sd": 4.52, "meanTotal": 8.96, "n": 554, "resid": 0.03, "marModel": 3.3373, "marBase": 3.4296, "marGain": 2.7, "marMean": 0.8, "marActual": 3.43, "cover": {"a": -0.5721, "b": 0.3643, "brier": 0.2269, "brierBase": 0.2291, "gain": 1.0, "base": 35.6, "favBase": 39.3, "n": 1108}, "win": {"sd": 4.65, "brier": 0.2443, "brierBase": 0.248, "gain": 1.5, "favAcc": 55.0, "n": 554}, "tried": ["lineup strength", "bullpen", "recent form", "home field", "park factor bolted onto the projection"]};
