// AUTO-GENERATED by mlb_strikeouts.py -- do not edit by hand.
// Projected strikeouts: BF x K/BF x opponent, all shrunk to league.
// Held-out MAE 1.8219 vs 1.8499 for the pitcher's season mean (+1.5%). NOT yet tested against the closing line.
// Generated 2026-10-08T20:31:11+00:00
export type MlbK = { gameKey: string; game: string; commence: string; pitcher: string;
  team: string; teamAbbr: string; oppAbbr: string;
  opp: string; proj: number; bf: number; kRate: number; oppFactor: number;
  starts: number; seasonMean: number };

export const MLB_K: MlbK[] = [{"gameKey": "849832", "game": "Cleveland Guardians @ Chicago White Sox", "commence": "2026-10-09T00:00:00Z", "pitcher": "Parker Messick", "team": "Cleveland Guardians", "opp": "Chicago White Sox", "teamAbbr": "CLE", "oppAbbr": "CWS", "proj": 5.94, "bf": 22.1, "kRate": 0.2564, "oppFactor": 1.046, "starts": 32, "seasonMean": 6.03}];
