// AUTO-GENERATED by mlb_strikeouts.py -- do not edit by hand.
// Projected strikeouts: BF x K/BF x opponent, all shrunk to league.
// Held-out MAE 1.8219 vs 1.8499 for the pitcher's season mean (+1.5%). NOT yet tested against the closing line.
// Generated 2026-10-09T20:00:09+00:00
export type MlbK = { gameKey: string; game: string; commence: string; pitcher: string;
  team: string; teamAbbr: string; oppAbbr: string;
  opp: string; proj: number; bf: number; kRate: number; oppFactor: number;
  starts: number; seasonMean: number };

export const MLB_K: MlbK[] = [{"gameKey": "849831", "game": "Chicago White Sox @ Cleveland Guardians", "commence": "2026-10-11T00:00:00Z", "pitcher": "Sean Burke", "team": "Chicago White Sox", "opp": "Cleveland Guardians", "teamAbbr": "CWS", "oppAbbr": "CLE", "proj": 4.99, "bf": 21.0, "kRate": 0.2543, "oppFactor": 0.932, "starts": 27, "seasonMean": 5.74}];
