// AUTO-GENERATED by mlb_strikeouts.py -- do not edit by hand.
// Projected strikeouts: BF x K/BF x opponent, all shrunk to league.
// Held-out MAE 1.8219 vs 1.8499 for the pitcher's season mean (+1.5%). NOT yet tested against the closing line.
// Generated 2026-10-01T20:08:19+00:00
export type MlbK = { gameKey: string; game: string; commence: string; pitcher: string;
  team: string; teamAbbr: string; oppAbbr: string;
  opp: string; proj: number; bf: number; kRate: number; oppFactor: number;
  starts: number; seasonMean: number };

export const MLB_K: MlbK[] = [{"gameKey": "849844", "game": "Philadelphia Phillies @ Atlanta Braves", "commence": "2026-10-02T00:00:00Z", "pitcher": "Aaron Nola", "team": "Philadelphia Phillies", "opp": "Atlanta Braves", "teamAbbr": "PHI", "oppAbbr": "ATL", "proj": 5.02, "bf": 21.4, "kRate": 0.2369, "oppFactor": 0.992, "starts": 33, "seasonMean": 5.36}, {"gameKey": "849829", "game": "Chicago White Sox @ Cleveland Guardians", "commence": "2026-10-03T17:00:00Z", "pitcher": "Parker Messick", "team": "Cleveland Guardians", "opp": "Chicago White Sox", "teamAbbr": "CLE", "oppAbbr": "CWS", "proj": 5.94, "bf": 22.1, "kRate": 0.2564, "oppFactor": 1.046, "starts": 32, "seasonMean": 6.03}, {"gameKey": "849835", "game": "New York Yankees @ Tampa Bay Rays", "commence": "2026-10-03T22:30:00Z", "pitcher": "Drew Rasmussen", "team": "Tampa Bay Rays", "opp": "New York Yankees", "teamAbbr": "TB", "oppAbbr": "NYY", "proj": 6.61, "bf": 22.7, "kRate": 0.2578, "oppFactor": 1.129, "starts": 30, "seasonMean": 5.8}, {"gameKey": "849830", "game": "San Diego Padres @ Milwaukee Brewers", "commence": "2026-10-04T00:30:00Z", "pitcher": "Jacob Misiorowski", "team": "Milwaukee Brewers", "opp": "San Diego Padres", "teamAbbr": "MIL", "oppAbbr": "SD", "proj": 7.29, "bf": 19.9, "kRate": 0.3699, "oppFactor": 0.989, "starts": 30, "seasonMean": 8.4}];
