// AUTO-GENERATED by cfb_player_proj.py -- do not edit by hand.
// First-pass NCAAF player-prop projections: prior-season per-game baseline (line-blind)
// + historical over-rates vs the current book line. PRESEASON — not graded yet.
import type { PlayerProj } from "./playerProjections";
export const NCAAF_PROJ_SEASON = 2026;
export const NCAAF_PROJ_PRIOR = 2025;
export const NCAAF_PROJ_WEEK = 2;
export const NCAAF_PLAYER_PROJECTIONS: PlayerProj[] = [
  {"game": "Ohio State @ Texas", "commence": "2026-09-12T23:30:00.000Z", "player": "Julian Sayin", "team": "Ohio State", "pos": "QB", "cat": "passing", "market": "pass_yds", "book": 238.5, "proj": 243.3, "g": 18, "cOver": 8, "cG": 18, "pOver": 8, "pG": 14, "hOver": 6, "hG": 12, "rOver": 2, "rG": 6, "matchup": "good"},
  {"game": "Ohio State @ Texas", "commence": "2026-09-12T23:30:00.000Z", "player": "Julian Sayin", "team": "Ohio State", "pos": "QB", "cat": "passing", "market": "pass_tds", "book": 1.5, "proj": 2.1, "g": 18, "cOver": 9, "cG": 18, "pOver": 9, "pG": 14, "hOver": 5, "hG": 12, "rOver": 4, "rG": 6, "matchup": "good"},
  {"game": "Ohio State @ Texas", "commence": "2026-09-12T23:30:00.000Z", "player": "Arch Manning", "team": "Texas", "pos": "QB", "cat": "passing", "market": "pass_yds", "book": 247.5, "proj": 253.3, "g": 19, "cOver": 9, "cG": 19, "pOver": 7, "pG": 13, "hOver": 6, "hG": 14, "rOver": 3, "rG": 5, "matchup": "bad"},
  {"game": "Ohio State @ Texas", "commence": "2026-09-12T23:30:00.000Z", "player": "Arch Manning", "team": "Texas", "pos": "QB", "cat": "passing", "market": "pass_tds", "book": 1.5, "proj": 2.1, "g": 19, "cOver": 10, "cG": 19, "pOver": 7, "pG": 13, "hOver": 8, "hG": 14, "rOver": 2, "rG": 5, "matchup": "bad"},
];
