// AUTO-GENERATED by cfb_player_proj.py -- do not edit by hand.
// First-pass NCAAF player-prop projections: prior-season per-game baseline (line-blind)
// + historical over-rates vs the current book line. PRESEASON — not graded yet.
import type { PlayerProj } from "./playerProjections";
type NcaafProj = PlayerProj & { mu?: number | null };
export const NCAAF_PROJ_SEASON = 2026;
export const NCAAF_PROJ_PRIOR = 2025;
export const NCAAF_PROJ_WEEK = 6;
export const NCAAF_PLAYER_PROJECTIONS: NcaafProj[] = [];
