// AUTO-GENERATED by analysis/player_proj_export.py — do not edit by hand.
// Prior-season (2025) baseline projections: volume x position efficiency. PRESEASON —
// not graded against closing lines yet.
export interface PlayerProj { game: string; commence: string; player: string; team: string;
  pos: string; cat: string; market: string; book: number; proj: number; g: number;
  cOver: number; cG: number; pOver: number; pG: number }
export const PROJ_SEASON = 2026;
export const PROJ_WEEK = 1;
export const PROJ_PRIOR = 2025;
export const PLAYER_PROJECTIONS: PlayerProj[] = [
  {"game": "NE @ SEA", "commence": "2026-09-10T00:15:00+00:00", "player": "Drake Maye", "team": "NE", "pos": "QB", "cat": "passing", "market": "pass_yds", "book": 223.5, "proj": 204.2, "g": 17, "cOver": 20, "cG": 34, "pOver": 15, "pG": 21},
  {"game": "NE @ SEA", "commence": "2026-09-10T00:15:00+00:00", "player": "Sam Darnold", "team": "SEA", "pos": "QB", "cat": "passing", "market": "pass_yds", "book": 230.5, "proj": 198.0, "g": 17, "cOver": 42, "cG": 99, "pOver": 11, "pG": 20},
  {"game": "NE @ SEA", "commence": "2026-09-10T00:15:00+00:00", "player": "Jaxon Smith-Njigba", "team": "SEA", "pos": "WR", "cat": "receiving", "market": "rec_yds", "book": 84.5, "proj": 76.1, "g": 17, "cOver": 18, "cG": 54, "pOver": 14, "pG": 20},
  {"game": "NE @ SEA", "commence": "2026-09-10T00:15:00+00:00", "player": "Rashid Shaheed", "team": "SEA", "pos": "WR", "cat": "receiving", "market": "rec_yds", "book": 28.0, "proj": 40.5, "g": 18, "cOver": 31, "cG": 54, "pOver": 11, "pG": 21},
  {"game": "NE @ SEA", "commence": "2026-09-10T00:15:00+00:00", "player": "Cooper Kupp", "team": "SEA", "pos": "WR", "cat": "receiving", "market": "rec_yds", "book": 27.0, "proj": 34.7, "g": 16, "cOver": 111, "cG": 132, "pOver": 13, "pG": 19},
  {"game": "NE @ SEA", "commence": "2026-09-10T00:15:00+00:00", "player": "AJ Barner", "team": "SEA", "pos": "TE", "cat": "receiving", "market": "rec_yds", "book": 25.0, "proj": 29.2, "g": 17, "cOver": 15, "cG": 35, "pOver": 11, "pG": 20},
  {"game": "NE @ SEA", "commence": "2026-09-10T00:15:00+00:00", "player": "Jaxon Smith-Njigba", "team": "SEA", "pos": "WR", "cat": "receptions", "market": "receptions", "book": 6.5, "proj": 6.0, "g": 17, "cOver": 20, "cG": 54, "pOver": 13, "pG": 20},
  {"game": "NE @ SEA", "commence": "2026-09-10T00:15:00+00:00", "player": "Rashid Shaheed", "team": "SEA", "pos": "WR", "cat": "receptions", "market": "receptions", "book": 2.5, "proj": 3.2, "g": 18, "cOver": 31, "cG": 54, "pOver": 11, "pG": 21},
  {"game": "NE @ SEA", "commence": "2026-09-10T00:15:00+00:00", "player": "AJ Barner", "team": "SEA", "pos": "TE", "cat": "receptions", "market": "receptions", "book": 2.5, "proj": 2.9, "g": 17, "cOver": 15, "cG": 35, "pOver": 11, "pG": 20},
  {"game": "NE @ SEA", "commence": "2026-09-10T00:15:00+00:00", "player": "Cooper Kupp", "team": "SEA", "pos": "WR", "cat": "receptions", "market": "receptions", "book": 2.5, "proj": 2.8, "g": 16, "cOver": 111, "cG": 132, "pOver": 10, "pG": 19},
  {"game": "NE @ SEA", "commence": "2026-09-10T00:15:00+00:00", "player": "TreVeyon Henderson", "team": "NE", "pos": "RB", "cat": "rushing", "market": "rush_yds", "book": 37.0, "proj": 45.4, "g": 17, "cOver": 9, "cG": 21, "pOver": 9, "pG": 21},
  {"game": "NE @ SEA", "commence": "2026-09-10T00:15:00+00:00", "player": "Rhamondre Stevenson", "team": "NE", "pos": "RB", "cat": "rushing", "market": "rush_yds", "book": 40.0, "proj": 39.8, "g": 14, "cOver": 42, "cG": 75, "pOver": 9, "pG": 18},
  {"game": "NE @ SEA", "commence": "2026-09-10T00:15:00+00:00", "player": "Drake Maye", "team": "NE", "pos": "QB", "cat": "rushing", "market": "rush_yds", "book": 21.5, "proj": 26.6, "g": 17, "cOver": 22, "cG": 34, "pOver": 13, "pG": 21},
  {"game": "NE @ SEA", "commence": "2026-09-10T00:15:00+00:00", "player": "George Holani", "team": "SEA", "pos": "RB", "cat": "rushing", "market": "rush_yds", "book": 21.5, "proj": 9.4, "g": 10, "cOver": 2, "cG": 15, "pOver": 2, "pG": 12},
  {"game": "NE @ SEA", "commence": "2026-09-10T00:15:00+00:00", "player": "Sam Darnold", "team": "SEA", "pos": "QB", "cat": "rushing", "market": "rush_yds", "book": 5.5, "proj": 9.1, "g": 17, "cOver": 56, "cG": 104, "pOver": 7, "pG": 20},
  {"game": "SF @ LA", "commence": "2026-09-11T00:35:00+00:00", "player": "Matthew Stafford", "team": "LA", "pos": "QB", "cat": "passing", "market": "pass_yds", "book": 265.5, "proj": 247.8, "g": 17, "cOver": 80, "cG": 157, "pOver": 12, "pG": 20},
  {"game": "SF @ LA", "commence": "2026-09-11T00:35:00+00:00", "player": "Brock Purdy", "team": "SF", "pos": "QB", "cat": "passing", "market": "pass_yds", "book": 245.5, "proj": 222.7, "g": 9, "cOver": 30, "cG": 55, "pOver": 6, "pG": 11},
  {"game": "SF @ LA", "commence": "2026-09-11T00:35:00+00:00", "player": "Puka Nacua", "team": "LA", "pos": "WR", "cat": "receiving", "market": "rec_yds", "book": 90.5, "proj": 82.3, "g": 16, "cOver": 27, "cG": 50, "pOver": 11, "pG": 19},
  {"game": "SF @ LA", "commence": "2026-09-11T00:35:00+00:00", "player": "Christian McCaffrey", "team": "SF", "pos": "RB", "cat": "receiving", "market": "rec_yds", "book": 35.5, "proj": 43.9, "g": 17, "cOver": 71, "cG": 121, "pOver": 15, "pG": 19},
  {"game": "SF @ LA", "commence": "2026-09-11T00:35:00+00:00", "player": "Puka Nacua", "team": "LA", "pos": "WR", "cat": "receptions", "market": "receptions", "book": 7.5, "proj": 6.5, "g": 16, "cOver": 21, "cG": 50, "pOver": 10, "pG": 19},
  {"game": "SF @ LA", "commence": "2026-09-11T00:35:00+00:00", "player": "Christian McCaffrey", "team": "SF", "pos": "RB", "cat": "receptions", "market": "receptions", "book": 4.5, "proj": 6.0, "g": 17, "cOver": 75, "cG": 121, "pOver": 15, "pG": 19},
  {"game": "SF @ LA", "commence": "2026-09-11T00:35:00+00:00", "player": "Christian McCaffrey", "team": "SF", "pos": "RB", "cat": "rushing", "market": "rush_yds", "book": 59.5, "proj": 78.5, "g": 17, "cOver": 59, "cG": 121, "pOver": 8, "pG": 19},
  {"game": "SF @ LA", "commence": "2026-09-11T00:35:00+00:00", "player": "Kyren Williams", "team": "LA", "pos": "RB", "cat": "rushing", "market": "rush_yds", "book": 57.5, "proj": 65.3, "g": 17, "cOver": 39, "cG": 59, "pOver": 15, "pG": 20},
  {"game": "SF @ LA", "commence": "2026-09-11T00:35:00+00:00", "player": "Blake Corum", "team": "LA", "pos": "RB", "cat": "rushing", "market": "rush_yds", "book": 35.5, "proj": 36.6, "g": 17, "cOver": 13, "cG": 35, "pOver": 12, "pG": 20},
  {"game": "SF @ LA", "commence": "2026-09-11T00:35:00+00:00", "player": "Brock Purdy", "team": "SF", "pos": "QB", "cat": "rushing", "market": "rush_yds", "book": 14.5, "proj": 16.1, "g": 9, "cOver": 20, "cG": 57, "pOver": 7, "pG": 11},
];
