// AUTO-GENERATED by analysis/gen_ref_stats.py — do not edit.
// Active NFL crew chiefs 2021-2025. Penalty rate is a mild PERSISTENT tendency;
// scoring is historical, NOT predictive (crews don't reliably move totals).
export const REF_LEAGUE = {"total": 45.0, "over": 48, "pen": 12.0, "peny": 99};
export interface RefStat { name: string; games: number; total: number; over: number; pen: number; penY: number }
export const REF_STATS: RefStat[] = [
  {"name": "Alex Moore", "games": 16, "total": 50.7, "over": 62, "pen": 16.1, "penY": 127},
  {"name": "Clete Blakeman", "games": 80, "total": 44.5, "over": 48, "pen": 12.9, "penY": 104},
  {"name": "Shawn Hochuli", "games": 80, "total": 43.5, "over": 40, "pen": 12.9, "penY": 110},
  {"name": "Adrian Hill", "games": 79, "total": 44.2, "over": 48, "pen": 12.6, "penY": 105},
  {"name": "Alex Kemp", "games": 81, "total": 45.2, "over": 49, "pen": 12.6, "penY": 105},
  {"name": "Brad Rogers", "games": 80, "total": 44.5, "over": 48, "pen": 12.6, "penY": 104},
  {"name": "Carl Cheffers", "games": 78, "total": 45.8, "over": 53, "pen": 12.6, "penY": 106},
  {"name": "Tra Blake", "games": 48, "total": 44.4, "over": 56, "pen": 12.2, "penY": 99},
  {"name": "Ron Torbert", "games": 80, "total": 44.1, "over": 44, "pen": 12.1, "penY": 99},
  {"name": "Shawn Smith", "games": 77, "total": 46.1, "over": 44, "pen": 12.0, "penY": 97},
  {"name": "Scott Novak", "games": 81, "total": 44.4, "over": 48, "pen": 11.9, "penY": 95},
  {"name": "Clay Martin", "games": 80, "total": 45.5, "over": 49, "pen": 11.8, "penY": 99},
  {"name": "Land Clark", "games": 80, "total": 44.8, "over": 50, "pen": 11.8, "penY": 99},
  {"name": "Craig Wrolstad", "games": 82, "total": 45.1, "over": 50, "pen": 11.6, "penY": 98},
  {"name": "Brad Allen", "games": 78, "total": 44.5, "over": 47, "pen": 11.4, "penY": 89},
  {"name": "Jerome Boger", "games": 32, "total": 44.8, "over": 41, "pen": 11.2, "penY": 89},
  {"name": "Bill Vinovich", "games": 81, "total": 46.0, "over": 48, "pen": 11.0, "penY": 88},
  {"name": "John Hussey", "games": 80, "total": 45.8, "over": 50, "pen": 11.0, "penY": 93},
  {"name": "Alan Eck", "games": 49, "total": 44.8, "over": 47, "pen": 10.8, "penY": 91},
  {"name": "Tony Corrente", "games": 16, "total": 49.1, "over": 62, "pen": 10.6, "penY": 87},
];
