// AUTO-GENERATED by analysis/gen_ref_stats.py — do not edit.
// Active NFL crew chiefs 2021-2025. Penalty rate is a mild PERSISTENT tendency;
// scoring, the favourite/underdog ATS split and the home/away split are all HISTORICAL
// -- what happened under that crew, not something measured to carry into the next game.
export const REF_LEAGUE = {"total": 45.0, "over": 48, "atsFav": 49, "homeWin": 54, "homeCover": 50, "pen": 11.7, "peny": 97};
export interface RefStat { name: string; games: number; total: number; over: number; atsFav: number; homeWin: number; homeCover: number; pen: number; penY: number }
export const REF_STATS: RefStat[] = [
  {"name": "Alex Moore", "games": 18, "total": 50.8, "over": 61, "atsFav": 56, "homeWin": 56, "homeCover": 56, "pen": 14.3, "penY": 113},
  {"name": "Shawn Hochuli", "games": 82, "total": 43.8, "over": 41, "atsFav": 44, "homeWin": 54, "homeCover": 48, "pen": 12.6, "penY": 107},
  {"name": "Alex Kemp", "games": 82, "total": 45.0, "over": 49, "atsFav": 57, "homeWin": 50, "homeCover": 44, "pen": 12.5, "penY": 104},
  {"name": "Clete Blakeman", "games": 82, "total": 44.4, "over": 46, "atsFav": 49, "homeWin": 57, "homeCover": 54, "pen": 12.5, "penY": 102},
  {"name": "Adrian Hill", "games": 81, "total": 43.7, "over": 47, "atsFav": 52, "homeWin": 48, "homeCover": 47, "pen": 12.3, "penY": 103},
  {"name": "Carl Cheffers", "games": 80, "total": 45.5, "over": 52, "atsFav": 46, "homeWin": 61, "homeCover": 54, "pen": 12.3, "penY": 103},
  {"name": "Brad Rogers", "games": 82, "total": 44.3, "over": 48, "atsFav": 51, "homeWin": 56, "homeCover": 53, "pen": 12.2, "penY": 102},
  {"name": "Tra Blake", "games": 48, "total": 44.4, "over": 56, "atsFav": 43, "homeWin": 52, "homeCover": 45, "pen": 12.2, "penY": 99},
  {"name": "Ron Torbert", "games": 82, "total": 44.4, "over": 44, "atsFav": 56, "homeWin": 57, "homeCover": 47, "pen": 11.8, "penY": 97},
  {"name": "Shawn Smith", "games": 79, "total": 46.1, "over": 46, "atsFav": 43, "homeWin": 53, "homeCover": 57, "pen": 11.7, "penY": 94},
  {"name": "Scott Novak", "games": 83, "total": 44.6, "over": 48, "atsFav": 46, "homeWin": 49, "homeCover": 45, "pen": 11.6, "penY": 93},
  {"name": "Clay Martin", "games": 82, "total": 45.5, "over": 49, "atsFav": 44, "homeWin": 52, "homeCover": 52, "pen": 11.5, "penY": 97},
  {"name": "Land Clark", "games": 82, "total": 44.3, "over": 49, "atsFav": 46, "homeWin": 39, "homeCover": 44, "pen": 11.5, "penY": 96},
  {"name": "Craig Wrolstad", "games": 84, "total": 45.3, "over": 51, "atsFav": 51, "homeWin": 52, "homeCover": 51, "pen": 11.3, "penY": 96},
  {"name": "Jerome Boger", "games": 32, "total": 44.8, "over": 41, "atsFav": 63, "homeWin": 56, "homeCover": 47, "pen": 11.2, "penY": 89},
  {"name": "Brad Allen", "games": 80, "total": 45.0, "over": 48, "atsFav": 48, "homeWin": 58, "homeCover": 47, "pen": 11.1, "penY": 87},
  {"name": "Bill Vinovich", "games": 82, "total": 46.0, "over": 48, "atsFav": 39, "homeWin": 43, "homeCover": 38, "pen": 10.8, "penY": 87},
  {"name": "John Hussey", "games": 82, "total": 45.9, "over": 50, "atsFav": 54, "homeWin": 71, "homeCover": 64, "pen": 10.7, "penY": 90},
  {"name": "Tony Corrente", "games": 16, "total": 49.1, "over": 62, "atsFav": 67, "homeWin": 56, "homeCover": 40, "pen": 10.6, "penY": 87},
  {"name": "Alan Eck", "games": 51, "total": 45.0, "over": 47, "atsFav": 67, "homeWin": 69, "homeCover": 57, "pen": 10.4, "penY": 88},
];
