// AUTO-GENERATED by analysis/team_ratings_export.py — do not edit by hand.
// Current-season points-per-game (offense = scored, defense = allowed) + league rank.
// CONTEXT, not a pick. Empty until the season"s games are played.
export interface TeamRating { team: string; off: number; def: number;
  offRank: number; defRank: number; games: number }
export const RATINGS_SEASON = 2026;
export const TEAM_RATINGS: Record<string, TeamRating> = {
};
