// AUTO-GENERATED by weather_capture.py — do not edit by hand.
// Game-site weather (Open-Meteo). CONTEXT, not a pick. Forecasts land ~16 days out.
export interface GameWeather { eventId: string; game: string; home: string; away: string;
  commence: string; neutral: boolean; venue: string; city: string|null; state: string|null;
  roof: 'outdoor'|'dome'|'retractable'; indoor: boolean;
  status: 'ok'|'pending'|'indoor'; tempF: number|null; windMph: number|null;
  gustMph: number|null; precipPct: number|null; conditions: string|null; windFlag: boolean }
export const WEATHER_SEASON = 2026;
export const WEATHER_WEEK = 3;
export const WEATHER_UPDATED = "2026-09-28T16:24Z";
export const GAME_WEATHER: GameWeather[] = [
  {"eventId": "47dc7baa254659f3beb2ed2b38c207b6", "game": "PHI @ CHI", "home": "CHI", "away": "PHI", "commence": "2026-09-29T00:15:00+00:00", "neutral": false, "venue": "Soldier Field", "city": "Chicago", "state": "IL", "roof": "outdoor", "indoor": false, "status": "ok", "tempF": 62, "windMph": 4, "gustMph": 7, "precipPct": 1, "conditions": "Clear", "windFlag": false},
];
