// AUTO-GENERATED by weather_capture.py — do not edit by hand.
// Game-site weather (Open-Meteo). CONTEXT, not a pick. Forecasts land ~16 days out.
export interface GameWeather { eventId: string; game: string; home: string; away: string;
  commence: string; neutral: boolean; venue: string; city: string|null; state: string|null;
  roof: 'outdoor'|'dome'|'retractable'; indoor: boolean;
  status: 'ok'|'pending'|'indoor'; tempF: number|null; windMph: number|null;
  gustMph: number|null; precipPct: number|null; conditions: string|null; windFlag: boolean }
export const WEATHER_SEASON = 2026;
export const WEATHER_WEEK = 1;
export const WEATHER_UPDATED = "2026-09-14T20:07Z";
export const GAME_WEATHER: GameWeather[] = [
  {"eventId": "5ad8135dc2b5f27de0b777acd317855a", "game": "DEN @ KC", "home": "KC", "away": "DEN", "commence": "2026-09-15T00:15:00+00:00", "neutral": false, "venue": "Arrowhead Stadium", "city": "Kansas City", "state": "MO", "roof": "outdoor", "indoor": false, "status": "ok", "tempF": 91, "windMph": 16, "gustMph": 33, "precipPct": 0, "conditions": "Clear", "windFlag": true},
];
