"""
cfb_export.py -- freeze the CFB power rating + its honest track record into a typed
data module the web app imports for the /ncaaf Model panel. No fabrication: every
number is computed here from data/cfb.db and written verbatim.

Writes web/app/ncaaf/model-data.ts. Re-run whenever the backfill refreshes.

    python cfb_export.py

Stdlib + numpy; reuses cfb_power / cfb_ats.
"""
import json
import sqlite3
import sys

import cfb_power as cp
import cfb_ats as ca

DB = "data/cfb.db"
LAM, CAP, DECAY, FROM_WEEK = 5.0, 28, 0.6, 6
OUT = "web/app/ncaaf/model-data.ts"


def team_conferences(db, season):
    conn = sqlite3.connect(db)
    rows = conn.execute(
        """SELECT home_team AS t, home_conf AS c FROM games
             WHERE season=? AND home_class='fbs' AND home_conf IS NOT NULL
           UNION
           SELECT away_team AS t, away_conf AS c FROM games
             WHERE season=? AND away_class='fbs' AND away_conf IS NOT NULL""",
        (season, season)).fetchall()
    conn.close()
    return {t: c for t, c in rows}


def season_final_ratings(games, upto):
    """Chain the carryover through seasons and return `upto` season's final rating+hfa."""
    seasons = sorted({g["season"] for g in games})
    prior, final, hfa = {}, {}, 0.0
    for s in seasons:
        sg = [g for g in games if g["season"] == s]
        final, hfa = cp.fit_ratings(sg, LAM, CAP, prior)
        prior = {t: DECAY * r for t, r in final.items()}
        if s == upto:
            break
    return final, hfa


def main():
    games = cp.load_games(DB, 2020, 2024)
    if not games:
        print("No games -- run cfb_backfill.py first.", file=sys.stderr)
        return 1
    last = max(g["season"] for g in games)

    final, hfa = season_final_ratings(games, last)
    confs = team_conferences(DB, last)
    ranked = sorted(final.items(), key=lambda kv: kv[1], reverse=True)
    top = [{"rank": i + 1, "team": t, "conf": confs.get(t, ""), "rating": round(r, 1)}
           for i, (t, r) in enumerate(ranked[:25])]

    res, se, ae = cp.walk_forward(games, LAM, CAP, FROM_WEEK, DECAY)
    n = res["n"]
    valid = {
        "games": n,
        "ourSU": round(100.0 * res["ours_su"] / n, 1),
        "eloSU": round(100.0 * res["elo_su"] / n, 1),
        "homeSU": round(100.0 * res["home_su"] / n, 1),
        "ourRMSE": round((se["ours"] / n) ** 0.5, 2),
        "eloRMSE": round((se["elo"] / n) ** 0.5, 2),
    }

    lined = ca.load(DB, 2020, 2024)
    tally = ca.backtest(lined, LAM, CAP, FROM_WEEK, DECAY)
    w, l, p = tally[0.0]
    ats = {"bets": w + l + p, "wins": w, "losses": l,
           "atsPct": round(100.0 * w / (w + l), 1), "breakeven": ca.BREAKEVEN}

    data = {
        "season": last, "seasons": "2020-2024", "hfa": round(hfa, 1),
        "teamsRated": len(final), "top": top, "validation": valid, "ats": ats,
    }
    body = ("// AUTO-GENERATED by cfb_export.py -- do not edit by hand.\n"
            "// Real, out-of-sample numbers from the CFB power rating over data/cfb.db.\n"
            "export type NcaafTeam = { rank: number; team: string; conf: string; rating: number };\n"
            "export const NCAAF_MODEL = " + json.dumps(data, indent=2) + " as const;\n")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"Wrote {OUT}")
    print(f"  {last} season: {len(final)} teams rated, HFA {hfa:.1f} pts")
    print(f"  #1 {top[0]['team']} ({top[0]['rating']}), #2 {top[1]['team']} ({top[1]['rating']})")
    print(f"  validation: our SU {valid['ourSU']}% vs Elo {valid['eloSU']}%; "
          f"ATS {ats['atsPct']}% (breakeven {ca.BREAKEVEN})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
