"""
cfb_weather.py -- NCAAF game-site weather (Open-Meteo), the college analog of weather_capture.py.

Maps each week's FBS games (CFBD /games) to the ACTUAL game venue (CFBD /venues, so neutral
sites like kickoff classics resolve to the real stadium, not the home team's), pulls the
hourly forecast nearest kickoff, and writes web/lib/cfbWeatherData.ts. Wind is the one
measured signal (the market under-sets totals ~1.3 pts at 15+ mph); this is CONTEXT, not a
pick. Domes are weather non-factors. Forecasts land ~16 days out, so far-off games are pending.

    python cfb_weather.py                 # current week (auto-detected)
    python cfb_weather.py --week 1        # explicit week

Auth: CFBD_API_KEY in .env. Reuses weather_capture.fetch_weather (Open-Meteo, no key).
"""
import argparse
import json
import os
import sys
from datetime import datetime, timezone

import cfbd_client as cc
import odds_client as oc
import weather_capture as wc   # reuse the Open-Meteo fetch + WMO code map

CUR_SEASON = 2026


def detect_week(key, season):
    """The current CFB week from the calendar (the first week whose games haven't all kicked
    off yet); defaults to 1."""
    try:
        st, cal = cc.cfbd_get("/calendar", {"year": season}, key)
        now = datetime.now(timezone.utc).isoformat()
        for w in cal or []:
            if (w.get("lastGameStart") or "") >= now:
                return int(w.get("week") or 1)
        if cal:
            return int(cal[-1].get("week") or 1)
    except Exception:                                        # noqa: BLE001
        pass
    return 1


def build(season, week, key):
    st, games = cc.cfbd_get("/games", {"year": season, "week": week, "classification": "fbs"}, key)
    if st != 200 or not isinstance(games, list):
        return []
    st, venues = cc.cfbd_get("/venues", {}, key)
    vmap = {v["id"]: v for v in (venues or []) if v.get("id")}
    rows, forecasted = [], 0
    for g in sorted(games, key=lambda x: x.get("startDate") or ""):
        home, away = g.get("homeTeam"), g.get("awayTeam")
        if not (home and away):
            continue
        v = vmap.get(g.get("venueId")) or {}
        dome = bool(v.get("dome"))
        commence = g.get("startDate")
        when = None
        if commence:
            try:
                when = datetime.fromisoformat(commence.replace("Z", "+00:00"))
            except ValueError:
                when = None
        rec = {
            "game": f"{away} @ {home}", "home": home, "away": away, "commence": commence,
            "neutral": bool(g.get("neutralSite")), "venue": v.get("name"),
            "city": v.get("city"), "state": v.get("state"),
            "roof": "dome" if dome else "outdoor", "indoor": dome,
            "status": "indoor" if dome else "pending",
            "tempF": None, "windMph": None, "gustMph": None, "precipPct": None,
            "conditions": None, "windFlag": False,
        }
        if not dome and v.get("latitude") and v.get("longitude") and when is not None:
            w = wc.fetch_weather(v["latitude"], v["longitude"], when)
            if w and w.get("windMph") is not None:
                rec.update(w)
                rec["status"] = "ok"
                rec["windFlag"] = (w.get("windMph") or 0) >= 15
                forecasted += 1
        rows.append(rec)
    print(f"  {len(rows)} games, {forecasted} with a live forecast (rest indoor or >16 days out)")
    return rows


def write_ts(rows, out, season, week):
    updated = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%MZ")
    body = (
        "// AUTO-GENERATED by cfb_weather.py -- do not edit by hand.\n"
        "// College game-site weather (Open-Meteo). CONTEXT, not a pick. Wind is the one measured\n"
        "// signal; domes are non-factors; forecasts land ~16 days out. Keyed by '{away} @ {home}'.\n"
        "export interface CfbGameWeather { game: string; home: string; away: string;\n"
        "  commence: string|null; neutral: boolean; venue: string|null; city: string|null;\n"
        "  state: string|null; roof: 'outdoor'|'dome'; indoor: boolean;\n"
        "  status: 'ok'|'pending'|'indoor'; tempF: number|null; windMph: number|null;\n"
        "  gustMph: number|null; precipPct: number|null; conditions: string|null; windFlag: boolean }\n"
        f"export const CFB_WEATHER_SEASON = {season};\n"
        f"export const CFB_WEATHER_WEEK = {week};\n"
        f'export const CFB_WEATHER_UPDATED = "{updated}";\n'
        "export const CFB_GAME_WEATHER: CfbGameWeather[] = [\n"
        + "".join("  " + json.dumps(r) + ",\n" for r in rows)
        + "];\n"
    )
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"Wrote {out} ({len(rows)} games).")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--season", type=int, default=CUR_SEASON)
    ap.add_argument("--week", type=int)
    ap.add_argument("--out", default="web/lib/cfbWeatherData.ts")
    args = ap.parse_args(argv)
    oc.ensure_ssl_certs()
    key = oc.load_env().get("CFBD_API_KEY")
    if not key:
        print("ERROR: CFBD_API_KEY missing", file=sys.stderr); return 1
    week = args.week or detect_week(key, args.season)
    print(f"CFB weather -- season {args.season}, week {week}")
    rows = build(args.season, week, key)
    write_ts(rows, args.out, args.season, week)
    return 0


if __name__ == "__main__":
    sys.exit(main())
