"""
chaos_traits.py -- per-team "chaos" traits for the SPECULATIVE Upset Lab / Chaos Board.

This is NOT a predictive model and never feeds The Model or Value Finder. It measures two
size-independent flavors that make a game feel upset-ripe, from the last two completed
seasons of margins:

  * volatility  -- std of a team's game margins. A boom/bust FAVORITE is more crashable.
  * ceiling     -- a team's best single-game margin. A high-ceiling DOG can go off.

Each is also expressed as a league percentile (0-100) so the Chaos Index can blend them
without re-normalizing in the browser. Written for both sports into web/lib/chaosTraits.ts.
NFL keys are the Odds-API full team names (so the live board joins directly); NCAAF keys
are CFBD names (matching model-data.ts). Stdlib + pandas (NFL) + sqlite3 (NCAAF).

    python analysis/chaos_traits.py
"""
import json
import sqlite3
import statistics
import sys

import pandas as pd

OUT = "web/lib/chaosTraits.ts"
WINDOW = 2  # last N completed seasons


def _traits_from_margins(by_team):
    """by_team: {team: [margins]} -> {team: {vol, ceiling, g, volPct, ceilPct}} with
    league percentiles. Teams with <6 games are kept but flagged thin (g)."""
    raw = {}
    for t, ms in by_team.items():
        if len(ms) < 3:
            continue
        raw[t] = {"vol": round(statistics.pstdev(ms), 1), "ceiling": int(max(ms)), "g": len(ms)}
    def pct_rank(vals):
        order = sorted(vals)
        n = len(order)
        return {v: (0.0 if n < 2 else round(100.0 * order.index(v) / (n - 1), 0)) for v in set(vals)}
    volp = pct_rank([r["vol"] for r in raw.values()])
    ceilp = pct_rank([r["ceiling"] for r in raw.values()])
    for r in raw.values():
        r["volPct"] = volp[r["vol"]]
        r["ceilPct"] = ceilp[r["ceiling"]]
    return raw


def nfl_traits(path="data/games.csv"):
    g = pd.read_csv(path, low_memory=False).dropna(subset=["home_score", "away_score"])
    seasons = sorted(g.season.unique())[-WINDOW:]
    g = g[g.season.isin(seasons)]
    by = {}
    for _, r in g.iterrows():
        m = int(r.home_score) - int(r.away_score)
        by.setdefault(r.home_team, []).append(m)
        by.setdefault(r.away_team, []).append(-m)
    # Keyed by nflverse abbr (ARI, LAC, ...), which is exactly what the live odds board and
    # its moneylines use, so the page joins directly.
    return _traits_from_margins(by), seasons


def cfb_traits(db="data/cfb.db"):
    conn = sqlite3.connect(db)
    seasons = [s for (s,) in conn.execute(
        "SELECT DISTINCT season FROM games WHERE home_points IS NOT NULL ORDER BY season DESC LIMIT ?",
        (WINDOW,))]
    rows = conn.execute(
        """SELECT home_team, away_team, home_points, away_points FROM games
             WHERE season IN (%s) AND home_class='fbs' AND away_class='fbs'
               AND home_points IS NOT NULL""" % ",".join("?" * len(seasons)), seasons).fetchall()
    conn.close()
    by = {}
    for h, a, hp, ap in rows:
        by.setdefault(h, []).append(hp - ap)
        by.setdefault(a, []).append(ap - hp)
    return _traits_from_margins(by), sorted(seasons)


def main():
    nfl, nfl_seasons = nfl_traits()
    cfb, cfb_seasons = cfb_traits()
    body = (
        "// AUTO-GENERATED by analysis/chaos_traits.py -- do not edit by hand.\n"
        "// Speculative 'Chaos Board' traits (margin volatility + ceiling) over the last two\n"
        "// completed seasons. NOT predictive; never feeds The Model or Value Finder.\n"
        "export interface ChaosTrait { vol: number; ceiling: number; g: number; volPct: number; ceilPct: number }\n"
        f"export const CHAOS_WINDOW = {json.dumps([str(s) for s in nfl_seasons])} as const;\n"
        f"export const NFL_CHAOS: Record<string, ChaosTrait> = {json.dumps(nfl, indent=0)};\n"
        f"export const CFB_CHAOS: Record<string, ChaosTrait> = {json.dumps(cfb, indent=0)};\n"
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"wrote {OUT}")
    print(f"  NFL: {len(nfl)} teams over {nfl_seasons}")
    print(f"  CFB: {len(cfb)} teams over {cfb_seasons}")
    # peek: most and least volatile NFL team
    if nfl:
        srt = sorted(nfl.items(), key=lambda kv: kv[1]["vol"])
        print(f"  steadiest: {srt[0][0]} (vol {srt[0][1]['vol']}); wildest: {srt[-1][0]} (vol {srt[-1][1]['vol']})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
