"""
depth_export.py -- freeze the current NFL offensive depth chart into web/lib/depthChart.ts
so the site can tell a realistic contributor from a deep backup.

The problem this solves: fan chatter and posted props surface backups and camp bodies who
won't actually get usage (e.g. a QB3 "over passing TDs"). nflverse publishes a depth chart
with pos_rank (1 = starter). We keep offensive skill positions (QB/RB/WR/TE/FB), take the
LATEST snapshot per player, and write a name -> {team, pos, rank} map plus an isRealistic()
helper the frontend uses to drop clear non-contributors.

    python analysis/depth_export.py            # build + write web/lib/depthChart.ts

Reads nflverse (public, no key). Stdlib only (+ odds_client for TLS/env reuse).
"""
import csv
import io
import os
import re
import sys
import urllib.error
import urllib.request

try:
    import certifi
    os.environ.setdefault("SSL_CERT_FILE", certifi.where())
except Exception:
    pass

SEASON = int(os.environ.get("SEASON", "2026"))
URL = ("https://github.com/nflverse/nflverse-data/releases/download/"
       "depth_charts/depth_charts_{season}.csv")
OUT = os.path.join("web", "lib", "depthChart.ts")
SKILL = {"QB", "RB", "WR", "TE", "FB"}
UA = {"User-Agent": "statseer-depth/1.0"}


def norm(n: str) -> str:
    """Match web/lib/home.ts normName: lowercase, letters+spaces only, drop suffixes."""
    n = (n or "").lower()
    n = re.sub(r"[^a-z ]", "", n)
    n = re.sub(r"\b(jr|sr|ii|iii|iv|v)\b", "", n)
    return re.sub(r"\s+", " ", n).strip()


def fetch_rows(season):
    req = urllib.request.Request(URL.format(season=season), headers=UA)
    with urllib.request.urlopen(req, timeout=60) as r:
        return list(csv.DictReader(io.StringIO(r.read().decode("utf-8", "replace"))))


def main():
    try:
        rows = fetch_rows(SEASON)
    except urllib.error.HTTPError as e:
        if e.code == 404:
            print(f"no depth chart for {SEASON} yet (404) — leaving depthChart.ts as is")
            return 0
        raise

    # Keep offensive skill players; take the LATEST dt per player (gsis_id), so a
    # promotion/demotion during camp is reflected. Key the map by normalized name.
    latest = {}   # gsis_id -> row (max dt)
    for r in rows:
        if (r.get("pos_abb") or "").upper() not in SKILL:
            continue
        gid = r.get("gsis_id") or r.get("player_name")
        if not gid:
            continue
        if gid not in latest or (r.get("dt") or "") > (latest[gid].get("dt") or ""):
            latest[gid] = r

    depth = {}   # norm name -> (team, pos, rank)
    for r in latest.values():
        name = norm(r.get("player_name") or "")
        rank = r.get("pos_rank")
        if not name or not str(rank).strip().isdigit():
            continue
        team = (r.get("team") or "").upper()
        pos = (r.get("pos_abb") or "").upper()
        rank = int(rank)
        # If a name collides (rare), keep the better (lower) rank — the more realistic one.
        if name not in depth or rank < depth[name][2]:
            depth[name] = (team, pos, rank)

    items = sorted(depth.items())
    body = [
        "// AUTO-GENERATED by analysis/depth_export.py — do not edit by hand.",
        "// Current NFL offensive depth chart (nflverse). Used to drop deep backups from the",
        "// fan-analysis and player-model snapshots so we surface realistic bets, not camp bodies.",
        "export interface DepthEntry { team: string; pos: string; rank: number }",
        f"export const DEPTH_SEASON = {SEASON};",
        "export const DEPTH: Record<string, DepthEntry> = {",
    ]
    for name, (team, pos, rank) in items:
        body.append(f'  {name!r}: {{ team: {team!r}, pos: {pos!r}, rank: {rank} }},')
    body.append("};")
    body.append("")
    body.append("// How deep at each position still counts as a realistic bettable role.")
    body.append("// Positions are NOT built the same, so caps are per-position:")
    body.append("//   QB 1  — only the starter throws; a QB2/QB3 (e.g. Ty Simpson) produces nothing unless the starter is hurt.")
    body.append("//   WR 4  — 3-4 WR sets are standard, so a WR3 (Cooper Kupp) or rotational WR4 still contributes; WR5+ are camp bodies.")
    body.append("//   TE 2  — 12-personnel means a receiving TE2 (Tyler Higbee) plays real snaps; TE3+ are blocking depth.")
    body.append("//   RB 3  — committee/change-of-pace/3rd-down backs all touch the ball; RB4+ don't without an injury.")
    body.append("//   FB 1  — only the starting fullback sees goal-line/short-yardage work.")
    body.append("const REALISTIC_RANK: Record<string, number> = { QB: 1, RB: 3, WR: 4, TE: 2, FB: 1 };")
    body.append("")
    body.append("const norm = (n: string) =>")
    body.append('  n.toLowerCase().replace(/[^a-z ]/g, "").replace(/\\b(jr|sr|ii|iii|iv|v)\\b/g, "").replace(/\\s+/g, " ").trim();')
    body.append("")
    body.append("/** True if the player is a realistic contributor (a starter/rotational player),")
    body.append(" *  false only for a KNOWN deep backup. Unknown names pass (don't over-filter). */")
    body.append("export function isRealistic(name: string): boolean {")
    body.append("  const e = DEPTH[norm(name)];")
    body.append("  if (!e) return true;")
    body.append("  const cap = REALISTIC_RANK[e.pos];")
    body.append("  return cap == null ? true : e.rank <= cap;")
    body.append("}")
    body.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(body))
    kept = len(items)
    starters = sum(1 for _, (_, p, r) in items if r == 1)
    print(f"wrote {kept} skill players ({starters} pos-1 starters) -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
