"""
Referee crew reference for the Upset Watch (Context). For each ACTIVE crew chief,
their games' scoring and penalty tendencies over recent seasons.

Honest framing (matches referee_analysis.py's finding): PENALTY rates are a mild
PERSISTENT crew tendency (r~+0.27); SCORING under a crew is essentially NOISE and
does NOT predict future games. So we show both, but the UI labels scoring as
"historical, not predictive." Emits a TS map the Context page reads.

    python analysis/gen_ref_stats.py
"""
import json
import numpy as np
import pandas as pd

RECENT = 2021  # crews active from this season on
OUT = "web/lib/refStats.ts"


def load_penalties():
    frames = []
    for y in range(RECENT, 2026):
        d = pd.read_csv(f"data/tstats_{y}.csv", low_memory=False)
        frames.append(d[["season", "week", "team", "penalties", "penalty_yards"]])
    return pd.concat(frames, ignore_index=True)


def main():
    g = pd.read_csv("data/games.csv", low_memory=False)
    g = g[(g.game_type == "REG") & g.home_score.notna() & g.referee.notna()
          & (g.season >= RECENT)].copy()
    g["total"] = g.home_score + g.away_score
    g["over"] = (g.total > g.total_line).astype(float)
    # favorite ATS: did the favored side cover? (nflverse spread_line >= 0 => home fav)
    margin = g.home_score - g.away_score
    fav_margin = np.where(g.spread_line >= 0, margin, -margin)
    fav_mag = g.spread_line.abs()
    g["favcover"] = np.where(g.spread_line.isna() | (fav_margin == fav_mag), np.nan,
                             (fav_margin > fav_mag).astype(float))
    # HOME/AWAY split, asked for alongside the favourite/underdog one ("what about whether they
    # favor home/away teams and take the points/take the spread?"). Same standing as the scoring
    # and ATS columns: HISTORY under that crew, not a tendency measured to carry over. The home
    # side wins ~55% and covers ~50% league-wide, so a crew is only interesting against those.
    # nflverse `spread_line` is the number the HOME side is laying (>= 0 means home favoured), so
    # the home team covers when its margin beats that number, and a push is excluded.
    g["homewin"] = np.where(margin == 0, np.nan, (margin > 0).astype(float))
    g["homecover"] = np.where(g.spread_line.isna() | (margin == g.spread_line), np.nan,
                              (margin > g.spread_line).astype(float))

    # penalties per game = home + away team penalties (from tstats)
    pen = load_penalties()
    gm = g.merge(pen.rename(columns={"team": "home_team", "penalties": "hp", "penalty_yards": "hpy"}),
                 on=["season", "week", "home_team"], how="left")
    gm = gm.merge(pen.rename(columns={"team": "away_team", "penalties": "ap", "penalty_yards": "apy"}),
                  on=["season", "week", "away_team"], how="left")
    gm["pen"] = gm.hp.fillna(0) + gm.ap.fillna(0)
    gm["peny"] = gm.hpy.fillna(0) + gm.apy.fillna(0)

    lg = {"total": round(gm.total.mean(), 1), "over": round(gm.over.mean() * 100),
          "atsFav": round(gm.favcover.mean() * 100),
          "homeWin": round(gm.homewin.mean() * 100),
          "homeCover": round(gm.homecover.mean() * 100),
          "pen": round(gm.pen.mean(), 1), "peny": round(gm.peny.mean())}

    rows = []
    for ref, s in gm.groupby("referee"):
        if len(s) < 12:  # need a real sample
            continue
        rows.append({
            "name": ref, "games": int(len(s)),
            "total": round(float(s.total.mean()), 1),
            "over": round(float(s.over.mean()) * 100),
            "atsFav": round(float(s.favcover.mean()) * 100),
            "homeWin": round(float(s.homewin.mean()) * 100),
            "homeCover": round(float(s.homecover.mean()) * 100),
            "pen": round(float(s.pen.mean()), 1),
            "penY": round(float(s.peny.mean())),
        })
    rows.sort(key=lambda r: -r["pen"])  # penalties = the persistent signal, lead with it

    lines = [
        "// AUTO-GENERATED by analysis/gen_ref_stats.py — do not edit.",
        f"// Active NFL crew chiefs {RECENT}-2025. Penalty rate is a mild PERSISTENT tendency;",
        "// scoring, the favourite/underdog ATS split and the home/away split are all HISTORICAL",
        "// -- what happened under that crew, not something measured to carry into the next game.",
        f"export const REF_LEAGUE = {json.dumps(lg)};",
        "export interface RefStat { name: string; games: number; total: number; over: number;"
        " atsFav: number; homeWin: number; homeCover: number; pen: number; penY: number }",
        "export const REF_STATS: RefStat[] = [",
    ]
    for r in rows:
        lines.append(f"  {json.dumps(r)},")
    lines.append("];")
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {len(rows)} crews to {OUT}")
    print("league avg:", lg)
    print("most penalized crew:", rows[0]["name"], rows[0]["pen"], "pen/g")
    print("least penalized crew:", rows[-1]["name"], rows[-1]["pen"], "pen/g")


if __name__ == "__main__":
    main()
