"""
Precompute the line-blind MODEL TOTAL for every 2026 game and emit a small TS map
the Context page imports. The totals model is weak (see totals_model.py / Empirical
§3) — this is an honest independent prediction, NOT an edge, and it's labeled that
way in the UI. Deterministic from 2025 (prior-season) data, so precomputing is fine.

    python analysis/gen_model_totals.py
"""
import pandas as pd
from totals_model import tendencies

SEASON = 2026
K = 0.50  # regression toward league total (best k from totals_model backtest)
OUT = "web/lib/modelTotals.ts"


def main():
    g = pd.read_csv("data/games.csv", low_memory=False)
    tend, Lt = tendencies(g, SEASON - 1)          # 2025 ratings
    sched = g[(g.season == SEASON) & (g.game_type == "REG")]

    rows = {}
    for _, r in sched.iterrows():
        h, a = r.home_team, r.away_team
        if h not in tend or a not in tend:
            continue
        pred = Lt + K * ((tend[h] + tend[a]) / 2 - Lt)
        rows[f"{int(r.week)}-{a}-{h}"] = round(float(pred), 1)

    lines = [
        "// AUTO-GENERATED by analysis/gen_model_totals.py — do not edit by hand.",
        "// Line-blind model total (combined points), keyed by `${week}-${away}-${home}`.",
        "// Weak by design (barely beats a league-average guess); shown as an honest",
        "// independent prediction, not an edge. See docs/EMPIRICAL_REFERENCE.md §3.",
        "export const MODEL_TOTALS: Record<string, number> = {",
    ]
    for k in sorted(rows, key=lambda x: (int(x.split("-")[0]), x)):
        lines.append(f'  "{k}": {rows[k]},')
    lines.append("};")
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {len(rows)} model totals to {OUT}  (2025 league avg total {Lt:.1f})")


if __name__ == "__main__":
    main()
