"""
team_ratings_export.py -- current-season offensive & defensive ratings per team, for the
Special Considerations cards. Writes web/lib/teamRatings.ts.

Rating = points per game (offense = scored, defense = allowed) over the CURRENT season's
completed regular-season games, plus each team's league rank. This is CONTEXT, not a pick
(per the project discipline) -- raw scoring, not opponent-adjusted. Preseason / before any
game is played -> no completed games -> empty file (nothing shows).

    python analysis/team_ratings_export.py            # build web/lib/teamRatings.ts

Reads the nflverse schedule (games.csv, with scores). Stdlib only (+ certifi for TLS).
"""
import csv
import io
import os
import sys
import urllib.error
import urllib.request

try:
    import certifi
    os.environ.setdefault("SSL_CERT_FILE", certifi.where())
except Exception:
    pass

SEASON = int(os.environ.get("SEASON", "2026"))
GAMES_LOCAL = os.path.join("data", "games.csv")
GAMES_URL = "https://raw.githubusercontent.com/nflverse/nfldata/master/data/games.csv"
OUT = os.path.join("web", "lib", "teamRatings.ts")
# nflverse abbr aliases -> the abbreviations the board/cards use.
ALIAS = {"LAR": "LA", "OAK": "LV", "SD": "LAC", "STL": "LA", "WSH": "WAS"}


def _rows():
    if os.path.exists(GAMES_LOCAL):
        with open(GAMES_LOCAL, "r", encoding="utf-8") as f:
            return list(csv.DictReader(f))
    req = urllib.request.Request(GAMES_URL, headers={"User-Agent": "statseer/1.0"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return list(csv.DictReader(io.StringIO(r.read().decode("utf-8", "replace"))))


def _num(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def main():
    try:
        rows = _rows()
    except Exception as e:  # noqa: BLE001 — no schedule -> empty ratings
        print(f"games.csv unavailable ({e}); wrote empty ratings", file=sys.stderr)
        rows = []

    # per team: [points scored, points allowed, games]
    #
    # Fall back to the PRIOR season when the current one has no completed games. The card read
    # "Off/def ratings arrive with the season" for the whole of Week 1 — technically honest and
    # useless exactly when a reader is looking at a Week 1 board. Last season's scoring rate is
    # the same kind of estimate the player projections already publish for Week 1: a prior-season
    # baseline, labelled as one. It stops being used the moment a real game is played.
    def _agg_for(season):
        a = {}
        for r in rows:
            if str(r.get("season")) != str(season) or r.get("game_type") != "REG":
                continue
            hs, as_ = _num(r.get("home_score")), _num(r.get("away_score"))
            if hs is None or as_ is None:
                continue   # not played yet
            home = ALIAS.get((r.get("home_team") or "").upper(), (r.get("home_team") or "").upper())
            away = ALIAS.get((r.get("away_team") or "").upper(), (r.get("away_team") or "").upper())
            for team, sc, ag in ((home, hs, as_), (away, as_, hs)):
                if not team:
                    continue
                t = a.setdefault(team, [0.0, 0.0, 0])
                t[0] += sc; t[1] += ag; t[2] += 1
        return a

    agg = _agg_for(SEASON)
    ratings_season, is_prior = SEASON, False
    if not agg:
        ratings_season, is_prior = SEASON - 1, True
        agg = _agg_for(ratings_season)
        print(f"no completed {SEASON} games — using {ratings_season} as the prior-season baseline")

    teams = []
    for team, (pf, pa, g) in agg.items():
        if g <= 0:
            continue
        teams.append({"team": team, "off": round(pf / g, 1), "def": round(pa / g, 1), "games": g})

    # league ranks: offense high-to-low (more points = better), defense low-to-high (fewer = better).
    for i, t in enumerate(sorted(teams, key=lambda x: -x["off"])):
        t["offRank"] = i + 1
    for i, t in enumerate(sorted(teams, key=lambda x: x["def"])):
        t["defRank"] = i + 1

    teams.sort(key=lambda x: x["team"])
    body = [
        "// AUTO-GENERATED by analysis/team_ratings_export.py — do not edit by hand.",
        "// Current-season points-per-game (offense = scored, defense = allowed) + league rank.",
        "// CONTEXT, not a pick. Falls back to the PRIOR season until this one has a played game;",
        "// RATINGS_IS_PRIOR says which, so the page can label it rather than imply it is current.",
        "export interface TeamRating { team: string; off: number; def: number;",
        "  offRank: number; defRank: number; games: number }",
        f"export const RATINGS_SEASON = {ratings_season};",
        f"export const RATINGS_IS_PRIOR = {'true' if is_prior else 'false'};",
        "export const TEAM_RATINGS: Record<string, TeamRating> = {",
    ]
    for t in teams:
        body.append("  %r: { team: %r, off: %s, def: %s, offRank: %s, defRank: %s, games: %s },"
                    % (t["team"], t["team"], t["off"], t["def"], t["offRank"], t["defRank"], t["games"]))
    body += ["};", ""]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(body).replace("'", '"'))
    print(f"wrote {len(teams)} team rating(s) for {SEASON} -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
