// AUTO-GENERATED by cfb_export.py -- do not edit by hand.
// Real, out-of-sample numbers from the CFB power rating over data/cfb.db.
export type NcaafTeam = { rank: number; team: string; conf: string; rating: number };
export type NcaafConf = { conf: string; avgRating: number; teams: number };
export type NcaafKeyNum = { margin: number; pct: number; nfl: number };
export type NcaafCardGame = { away: string; home: string; neutral: number; fav: string; margin: number; date: string };
export const NCAAF_MODEL = {
  "season": 2025,
  "seasons": "2020-2025",
  "hfa": 3.2,
  "teamsRated": 136,
  "top": [
    {
      "rank": 1,
      "team": "Indiana",
      "conf": "Big Ten",
      "rating": 20.3
    },
    {
      "rank": 2,
      "team": "Ohio State",
      "conf": "Big Ten",
      "rating": 20.2
    },
    {
      "rank": 3,
      "team": "Notre Dame",
      "conf": "FBS Independents",
      "rating": 17.7
    },
    {
      "rank": 4,
      "team": "Oregon",
      "conf": "Big Ten",
      "rating": 16.5
    },
    {
      "rank": 5,
      "team": "Texas Tech",
      "conf": "Big 12",
      "rating": 16.0
    },
    {
      "rank": 6,
      "team": "Miami",
      "conf": "ACC",
      "rating": 15.8
    },
    {
      "rank": 7,
      "team": "Georgia",
      "conf": "SEC",
      "rating": 13.7
    },
    {
      "rank": 8,
      "team": "Utah",
      "conf": "Big 12",
      "rating": 13.4
    },
    {
      "rank": 9,
      "team": "Ole Miss",
      "conf": "SEC",
      "rating": 12.7
    },
    {
      "rank": 10,
      "team": "Texas A&M",
      "conf": "SEC",
      "rating": 11.4
    },
    {
      "rank": 11,
      "team": "Iowa",
      "conf": "Big Ten",
      "rating": 10.6
    },
    {
      "rank": 12,
      "team": "Vanderbilt",
      "conf": "SEC",
      "rating": 10.3
    },
    {
      "rank": 13,
      "team": "James Madison",
      "conf": "Sun Belt",
      "rating": 10.3
    },
    {
      "rank": 14,
      "team": "BYU",
      "conf": "Big 12",
      "rating": 10.3
    },
    {
      "rank": 15,
      "team": "USC",
      "conf": "Big Ten",
      "rating": 10.2
    },
    {
      "rank": 16,
      "team": "Penn State",
      "conf": "Big Ten",
      "rating": 10.1
    },
    {
      "rank": 17,
      "team": "Texas",
      "conf": "SEC",
      "rating": 10.1
    },
    {
      "rank": 18,
      "team": "Alabama",
      "conf": "SEC",
      "rating": 9.9
    },
    {
      "rank": 19,
      "team": "SMU",
      "conf": "ACC",
      "rating": 9.7
    },
    {
      "rank": 20,
      "team": "Washington",
      "conf": "Big Ten",
      "rating": 9.6
    },
    {
      "rank": 21,
      "team": "Oklahoma",
      "conf": "SEC",
      "rating": 8.1
    },
    {
      "rank": 22,
      "team": "South Florida",
      "conf": "American Athletic",
      "rating": 7.8
    },
    {
      "rank": 23,
      "team": "Louisville",
      "conf": "ACC",
      "rating": 7.3
    },
    {
      "rank": 24,
      "team": "North Texas",
      "conf": "American Athletic",
      "rating": 7.2
    },
    {
      "rank": 25,
      "team": "Tennessee",
      "conf": "SEC",
      "rating": 7.0
    }
  ],
  "validation": {
    "games": 2822,
    "ourSU": 71.0,
    "eloSU": 70.6,
    "homeSU": 56.5,
    "ourRMSE": 16.43,
    "eloRMSE": 16.15
  },
  "ats": {
    "bets": 2306,
    "wins": 1126,
    "losses": 1157,
    "atsPct": 49.3,
    "breakeven": 52.38
  },
  "context": {
    "hfa": 3.2,
    "conferences": [
      {
        "conf": "SEC",
        "avgRating": 6.3,
        "teams": 16
      },
      {
        "conf": "Big Ten",
        "avgRating": 5.4,
        "teams": 18
      },
      {
        "conf": "Big 12",
        "avgRating": 3.3,
        "teams": 16
      },
      {
        "conf": "ACC",
        "avgRating": 1.7,
        "teams": 17
      },
      {
        "conf": "American Athletic",
        "avgRating": -2.6,
        "teams": 14
      },
      {
        "conf": "Mountain West",
        "avgRating": -3.2,
        "teams": 12
      },
      {
        "conf": "Sun Belt",
        "avgRating": -3.7,
        "teams": 14
      },
      {
        "conf": "Conference USA",
        "avgRating": -6.2,
        "teams": 12
      },
      {
        "conf": "Mid-American",
        "avgRating": -6.8,
        "teams": 13
      }
    ]
  },
  "value": {
    "games": 4478,
    "keyNumbers": [
      {
        "margin": 3,
        "pct": 10.6,
        "nfl": 15.0
      },
      {
        "margin": 7,
        "pct": 8.6,
        "nfl": 9.1
      },
      {
        "margin": 10,
        "pct": 4.6,
        "nfl": 5.8
      },
      {
        "margin": 14,
        "pct": 4.4,
        "nfl": 4.9
      }
    ],
    "bookShop": {
      "games": 3935,
      "avgRange": 0.78,
      "pctGap1": 30
    }
  },
  "card": {
    "season": 2026,
    "week": 1,
    "games": [
      {
        "away": "Louisville",
        "home": "Ole Miss",
        "neutral": 1,
        "fav": "Ole Miss",
        "margin": 3.2,
        "date": "2026-09-06"
      },
      {
        "away": "North Texas",
        "home": "Indiana",
        "neutral": 0,
        "fav": "Indiana",
        "margin": 11.1,
        "date": "2026-09-05"
      },
      {
        "away": "Clemson",
        "home": "LSU",
        "neutral": 0,
        "fav": "LSU",
        "margin": 2.7,
        "date": "2026-09-05"
      },
      {
        "away": "Washington State",
        "home": "Washington",
        "neutral": 0,
        "fav": "Washington",
        "margin": 6.2,
        "date": "2026-09-06"
      },
      {
        "away": "Boise State",
        "home": "Oregon",
        "neutral": 0,
        "fav": "Oregon",
        "margin": 10.6,
        "date": "2026-09-05"
      },
      {
        "away": "East Carolina",
        "home": "Alabama",
        "neutral": 0,
        "fav": "Alabama",
        "margin": 6.8,
        "date": "2026-09-05"
      },
      {
        "away": "Tulane",
        "home": "Duke",
        "neutral": 0,
        "fav": "Duke",
        "margin": 3.0,
        "date": "2026-09-05"
      },
      {
        "away": "Memphis",
        "home": "UNLV",
        "neutral": 0,
        "fav": "UNLV",
        "margin": 2.9,
        "date": "2026-08-30"
      },
      {
        "away": "NC State",
        "home": "Virginia",
        "neutral": 0,
        "fav": "Virginia",
        "margin": 4.7,
        "date": "2026-08-29"
      },
      {
        "away": "Texas State",
        "home": "Texas",
        "neutral": 0,
        "fav": "Texas",
        "margin": 7.9,
        "date": "2026-09-05"
      },
      {
        "away": "SMU",
        "home": "Florida State",
        "neutral": 0,
        "fav": "SMU",
        "margin": 1.5,
        "date": "2026-09-07"
      },
      {
        "away": "Western Michigan",
        "home": "Michigan",
        "neutral": 0,
        "fav": "Michigan",
        "margin": 7.2,
        "date": "2026-09-05"
      },
      {
        "away": "Ohio",
        "home": "Nebraska",
        "neutral": 0,
        "fav": "Nebraska",
        "margin": 2.3,
        "date": "2026-09-05"
      },
      {
        "away": "Baylor",
        "home": "Auburn",
        "neutral": 1,
        "fav": "Auburn",
        "margin": 2.5,
        "date": "2026-09-05"
      },
      {
        "away": "Fresno State",
        "home": "USC",
        "neutral": 0,
        "fav": "USC",
        "margin": 9.7,
        "date": "2026-09-05"
      },
      {
        "away": "Wisconsin",
        "home": "Notre Dame",
        "neutral": 1,
        "fav": "Notre Dame",
        "margin": 11.1,
        "date": "2026-09-06"
      }
    ]
  }
} as const;
