// AUTO-GENERATED by cfb_export.py -- do not edit by hand.
// Real, out-of-sample numbers from the CFB power rating over data/cfb.db.
export type NcaafTeam = { rank: number; team: string; conf: string; rating: number };
export type NcaafConf = { conf: string; avgRating: number; teams: number };
export type NcaafKeyNum = { margin: number; pct: number; nfl: number };
export type NcaafCardGame = { away: string; home: string; neutral: number; conf: string; commence?: string; marketSpread: { fav: string; num: number } | null; marketTotal: number | null; projSpread: { fav: string; num: number }; projTotal: number; homeRiser: number; awayRiser: number; pick: { side: string; num: number } | null; totalLean: { dir: string; num: number } | null; off: boolean; featured: boolean };
export type NcaafUpset = { dog: string; matchup: string; spread: string; modelPct: number; marketPct: number; byPoints: number };
export const NCAAF_MODEL = {
  "season": 2025,
  "seasons": "2020-2025",
  "hfa": 3.2,
  "teamsRated": 136,
  "top": [
    {
      "rank": 1,
      "team": "Indiana",
      "conf": "Big Ten",
      "rating": 20.3
    },
    {
      "rank": 2,
      "team": "Ohio State",
      "conf": "Big Ten",
      "rating": 20.2
    },
    {
      "rank": 3,
      "team": "Notre Dame",
      "conf": "FBS Independents",
      "rating": 17.7
    },
    {
      "rank": 4,
      "team": "Oregon",
      "conf": "Big Ten",
      "rating": 16.5
    },
    {
      "rank": 5,
      "team": "Texas Tech",
      "conf": "Big 12",
      "rating": 16.0
    },
    {
      "rank": 6,
      "team": "Miami",
      "conf": "ACC",
      "rating": 15.8
    },
    {
      "rank": 7,
      "team": "Georgia",
      "conf": "SEC",
      "rating": 13.7
    },
    {
      "rank": 8,
      "team": "Utah",
      "conf": "Big 12",
      "rating": 13.4
    },
    {
      "rank": 9,
      "team": "Ole Miss",
      "conf": "SEC",
      "rating": 12.7
    },
    {
      "rank": 10,
      "team": "Texas A&M",
      "conf": "SEC",
      "rating": 11.4
    },
    {
      "rank": 11,
      "team": "Iowa",
      "conf": "Big Ten",
      "rating": 10.6
    },
    {
      "rank": 12,
      "team": "Vanderbilt",
      "conf": "SEC",
      "rating": 10.3
    },
    {
      "rank": 13,
      "team": "James Madison",
      "conf": "Sun Belt",
      "rating": 10.3
    },
    {
      "rank": 14,
      "team": "BYU",
      "conf": "Big 12",
      "rating": 10.3
    },
    {
      "rank": 15,
      "team": "USC",
      "conf": "Big Ten",
      "rating": 10.2
    },
    {
      "rank": 16,
      "team": "Penn State",
      "conf": "Big Ten",
      "rating": 10.1
    },
    {
      "rank": 17,
      "team": "Texas",
      "conf": "SEC",
      "rating": 10.1
    },
    {
      "rank": 18,
      "team": "Alabama",
      "conf": "SEC",
      "rating": 9.9
    },
    {
      "rank": 19,
      "team": "SMU",
      "conf": "ACC",
      "rating": 9.7
    },
    {
      "rank": 20,
      "team": "Washington",
      "conf": "Big Ten",
      "rating": 9.6
    },
    {
      "rank": 21,
      "team": "Oklahoma",
      "conf": "SEC",
      "rating": 8.1
    },
    {
      "rank": 22,
      "team": "South Florida",
      "conf": "American Athletic",
      "rating": 7.8
    },
    {
      "rank": 23,
      "team": "Louisville",
      "conf": "ACC",
      "rating": 7.3
    },
    {
      "rank": 24,
      "team": "North Texas",
      "conf": "American Athletic",
      "rating": 7.2
    },
    {
      "rank": 25,
      "team": "Tennessee",
      "conf": "SEC",
      "rating": 7.0
    }
  ],
  "validation": {
    "games": 2822,
    "ourSU": 71.0,
    "eloSU": 70.6,
    "homeSU": 56.5,
    "ourRMSE": 16.43,
    "eloRMSE": 16.15
  },
  "ats": {
    "bets": 2306,
    "wins": 1126,
    "losses": 1157,
    "atsPct": 49.3,
    "breakeven": 52.38
  },
  "context": {
    "hfa": 3.2,
    "conferences": [
      {
        "conf": "SEC",
        "avgRating": 6.3,
        "teams": 16
      },
      {
        "conf": "Big Ten",
        "avgRating": 5.4,
        "teams": 18
      },
      {
        "conf": "Big 12",
        "avgRating": 3.3,
        "teams": 16
      },
      {
        "conf": "ACC",
        "avgRating": 1.7,
        "teams": 17
      },
      {
        "conf": "American Athletic",
        "avgRating": -2.6,
        "teams": 14
      },
      {
        "conf": "Mountain West",
        "avgRating": -3.2,
        "teams": 12
      },
      {
        "conf": "Sun Belt",
        "avgRating": -3.7,
        "teams": 14
      },
      {
        "conf": "Conference USA",
        "avgRating": -6.2,
        "teams": 12
      },
      {
        "conf": "Mid-American",
        "avgRating": -6.8,
        "teams": 13
      }
    ]
  },
  "value": {
    "games": 4478,
    "keyNumbers": [
      {
        "margin": 3,
        "pct": 10.6,
        "nfl": 15.0
      },
      {
        "margin": 7,
        "pct": 8.6,
        "nfl": 9.1
      },
      {
        "margin": 10,
        "pct": 4.6,
        "nfl": 5.8
      },
      {
        "margin": 14,
        "pct": 4.4,
        "nfl": 4.9
      }
    ],
    "bookShop": {
      "games": 4863,
      "avgRange": 0.77,
      "pctGap1": 30
    }
  },
  "card": {
    "season": 2026,
    "week": 1,
    "preseasonSeeded": true,
    "games": [
      {
        "away": "North Carolina",
        "home": "TCU",
        "neutral": 1,
        "commence": "2026-08-29T16:00:00.000Z",
        "conf": "Big 12",
        "marketSpread": {
          "fav": "TCU",
          "num": -9.0
        },
        "marketTotal": 47.0,
        "projSpread": {
          "fav": "TCU",
          "num": -9.0
        },
        "projTotal": 49.8,
        "homeRiser": 0,
        "awayRiser": 38,
        "pick": {
          "side": "North Carolina",
          "num": 9.0
        },
        "totalLean": {
          "dir": "OVER",
          "num": 47.0
        },
        "off": false,
        "featured": false
      },
      {
        "away": "San Jos\u00e9 State",
        "home": "USC",
        "neutral": 0,
        "commence": "2026-08-29T19:00:00.000Z",
        "conf": "Big Ten",
        "marketSpread": null,
        "marketTotal": null,
        "projSpread": {
          "fav": "USC",
          "num": -33.8
        },
        "projTotal": 55.8,
        "homeRiser": 2,
        "awayRiser": 0,
        "pick": null,
        "totalLean": null,
        "off": false,
        "featured": true
      },
      {
        "away": "NC State",
        "home": "Virginia",
        "neutral": 0,
        "commence": "2026-08-29T19:30:00.000Z",
        "conf": "ACC",
        "marketSpread": {
          "fav": "Virginia",
          "num": -4.0
        },
        "marketTotal": 53.0,
        "projSpread": {
          "fav": "Virginia",
          "num": -6.5
        },
        "projTotal": 52.6,
        "homeRiser": 0,
        "awayRiser": 6,
        "pick": {
          "side": "Virginia",
          "num": -4.0
        },
        "totalLean": null,
        "off": false,
        "featured": false
      },
      {
        "away": "Jacksonville State",
        "home": "North Dakota State",
        "neutral": 0,
        "commence": "2026-08-29T21:30:00.000Z",
        "conf": "Other",
        "marketSpread": {
          "fav": "North Dakota State",
          "num": -7.0
        },
        "marketTotal": 46.5,
        "projSpread": {
          "fav": "Jacksonville State",
          "num": -0.6
        },
        "projTotal": 52.7,
        "homeRiser": 0,
        "awayRiser": 0,
        "pick": {
          "side": "Jacksonville State",
          "num": 7.0
        },
        "totalLean": {
          "dir": "OVER",
          "num": 46.5
        },
        "off": true,
        "featured": false
      },
      {
        "away": "Sacramento State",
        "home": "Eastern Michigan",
        "neutral": 0,
        "commence": "2026-08-29T22:30:00.000Z",
        "conf": "Mid-American",
        "marketSpread": {
          "fav": "Eastern Michigan",
          "num": -9.5
        },
        "marketTotal": 54.0,
        "projSpread": {
          "fav": "Eastern Michigan",
          "num": -0.8
        },
        "projTotal": 53.1,
        "homeRiser": 0,
        "awayRiser": 0,
        "pick": {
          "side": "Sacramento State",
          "num": 9.5
        },
        "totalLean": null,
        "off": false,
        "featured": false
      },
      {
        "away": "Hawai'i",
        "home": "Stanford",
        "neutral": 0,
        "commence": "2026-08-29T23:00:00.000Z",
        "conf": "ACC",
        "marketSpread": null,
        "marketTotal": null,
        "projSpread": {
          "fav": "Stanford",
          "num": -2.4
        },
        "projTotal": 51.7,
        "homeRiser": 17,
        "awayRiser": 0,
        "pick": null,
        "totalLean": null,
        "off": false,
        "featured": false
      },
      {
        "away": "New Mexico State",
        "home": "Florida State",
        "neutral": 0,
        "commence": "2026-08-29T23:00:00.000Z",
        "conf": "ACC",
        "marketSpread": {
          "fav": "Florida State",
          "num": -31.0
        },
        "marketTotal": 53.5,
        "projSpread": {
          "fav": "Florida State",
          "num": -26.9
        },
        "projTotal": 52.2,
        "homeRiser": 14,
        "awayRiser": 0,
        "pick": {
          "side": "New Mexico State",
          "num": 31.0
        },
        "totalLean": null,
        "off": false,
        "featured": false
      },
      {
        "away": "Memphis",
        "home": "UNLV",
        "neutral": 0,
        "commence": "2026-08-30T02:00:00.000Z",
        "conf": "Mountain West",
        "marketSpread": {
          "fav": "UNLV",
          "num": -4.5
        },
        "marketTotal": 56.5,
        "projSpread": {
          "fav": "UNLV",
          "num": -5.8
        },
        "projTotal": 58.1,
        "homeRiser": 0,
        "awayRiser": 0,
        "pick": {
          "side": "UNLV",
          "num": -4.5
        },
        "totalLean": null,
        "off": false,
        "featured": false
      },
      {
        "away": "Massachusetts",
        "home": "Rutgers",
        "neutral": 0,
        "commence": "2026-09-03T22:00:00.000Z",
        "conf": "Big Ten",
        "marketSpread": null,
        "marketTotal": null,
        "projSpread": {
          "fav": "Rutgers",
          "num": -36.2
        },
        "projTotal": 54.2,
        "homeRiser": 4,
        "awayRiser": 0,
        "pick": null,
        "totalLean": null,
        "off": false,
        "featured": false
      },
      {
        "away": "Akron",
        "home": "Wake Forest",
        "neutral": 0,
        "commence": "2026-09-03T23:00:00.000Z",
        "conf": "ACC",
        "marketSpread": {
          "fav": "Wake Forest",
          "num": -24.0
        },
        "marketTotal": 48.5,
        "projSpread": {
          "fav": "Wake Forest",
          "num": -25.8
        },
        "projTotal": 49.8,
        "homeRiser": 5,
        "awayRiser": 0,
        "pick": {
          "side": "Wake Forest",
          "num": -24.0
        },
        "totalLean": null,
        "off": false,
        "featured": false
      },
      {
        "away": "Colorado",
        "home": "Georgia Tech",
        "neutral": 0,
        "commence": "2026-09-04T00:00:00.000Z",
        "conf": "ACC",
        "marketSpread": {
          "fav": "Georgia Tech",
          "num": -6.5
        },
        "marketTotal": 50.5,
        "projSpread": {
          "fav": "Georgia Tech",
          "num": -9.8
        },
        "projTotal": 53.6,
        "homeRiser": 1,
        "awayRiser": 12,
        "pick": {
          "side": "Georgia Tech",
          "num": -6.5
        },
        "totalLean": {
          "dir": "OVER",
          "num": 50.5
        },
        "off": false,
        "featured": false
      },
      {
        "away": "UAB",
        "home": "Illinois",
        "neutral": 0,
        "commence": "2026-09-04T01:00:00.000Z",
        "conf": "Big Ten",
        "marketSpread": {
          "fav": "Illinois",
          "num": -28.5
        },
        "marketTotal": 56.5,
        "projSpread": {
          "fav": "Illinois",
          "num": -29.7
        },
        "projTotal": 56.8,
        "homeRiser": 0,
        "awayRiser": 4,
        "pick": {
          "side": "Illinois",
          "num": -28.5
        },
        "totalLean": null,
        "off": false,
        "featured": false
      },
      {
        "away": "San Jos\u00e9 State",
        "home": "Eastern Michigan",
        "neutral": 0,
        "commence": "2026-09-04T22:30:00.000Z",
        "conf": "Mid-American",
        "marketSpread": null,
        "marketTotal": null,
        "projSpread": {
          "fav": "Eastern Michigan",
          "num": -4.1
        },
        "projTotal": 53.6,
        "homeRiser": 0,
        "awayRiser": 0,
        "pick": null,
        "totalLean": null,
        "off": false,
        "featured": false
      },
      {
        "away": "UTEP",
        "home": "Oklahoma",
        "neutral": 0,
        "commence": "2026-09-05T00:00:00.000Z",
        "conf": "SEC",
        "marketSpread": {
          "fav": "Oklahoma",
          "num": -41.5
        },
        "marketTotal": 50.5,
        "projSpread": {
          "fav": "Oklahoma",
          "num": -37.1
        },
        "projTotal": 48.1,
        "homeRiser": 8,
        "awayRiser": 4,
        "pick": {
          "side": "UTEP",
          "num": 41.5
        },
        "totalLean": {
          "dir": "UNDER",
          "num": 50.5
        },
        "off": false,
        "featured": true
      },
      {
        "away": "Toledo",
        "home": "Michigan State",
        "neutral": 0,
        "commence": "2026-09-05T00:00:00.000Z",
        "conf": "Big Ten",
        "marketSpread": {
          "fav": "Michigan State",
          "num": -10.0
        },
        "marketTotal": 49.5,
        "projSpread": {
          "fav": "Michigan State",
          "num": -7.6
        },
        "projTotal": 48.6,
        "homeRiser": 20,
        "awayRiser": 0,
        "pick": {
          "side": "Toledo",
          "num": 10.0
        },
        "totalLean": null,
        "off": false,
        "featured": false
      },
      {
        "away": "Fresno State",
        "home": "USC",
        "neutral": 0,
        "commence": "2026-09-05T01:00:00.000Z",
        "conf": "Big Ten",
        "marketSpread": {
          "fav": "USC",
          "num": -23.0
        },
        "marketTotal": 51.5,
        "projSpread": {
          "fav": "USC",
          "num": -20.9
        },
        "projTotal": 51.1,
        "homeRiser": 2,
        "awayRiser": 0,
        "pick": {
          "side": "Fresno State",
          "num": 23.0
        },
        "totalLean": null,
        "off": false,
        "featured": true
      },
      {
        "away": "Miami",
        "home": "Stanford",
        "neutral": 0,
        "commence": "2026-09-05T01:00:00.000Z",
        "conf": "ACC",
        "marketSpread": {
          "fav": "Miami",
          "num": -24.0
        },
        "marketTotal": 48.5,
        "projSpread": {
          "fav": "Miami",
          "num": -21.1
        },
        "projTotal": 47.2,
        "homeRiser": 17,
        "awayRiser": 0,
        "pick": {
          "side": "Stanford",
          "num": 24.0
        },
        "totalLean": null,
        "off": false,
        "featured": true
      },
      {
        "away": "East Carolina",
        "home": "Alabama",
        "neutral": 0,
        "commence": "2026-09-05T16:00:00.000Z",
        "conf": "SEC",
        "marketSpread": {
          "fav": "Alabama",
          "num": -28.5
        },
        "marketTotal": 54.0,
        "projSpread": {
          "fav": "Alabama",
          "num": -19.3
        },
        "projTotal": 50.4,
        "homeRiser": 4,
        "awayRiser": 0,
        "pick": {
          "side": "East Carolina",
          "num": 28.5
        },
        "totalLean": {
          "dir": "UNDER",
          "num": 54.0
        },
        "off": false,
        "featured": true
      },
      {
        "away": "North Texas",
        "home": "Indiana",
        "neutral": 0,
        "commence": "2026-09-05T16:00:00.000Z",
        "conf": "Big Ten",
        "marketSpread": {
          "fav": "Indiana",
          "num": -40.5
        },
        "marketTotal": 55.5,
        "projSpread": {
          "fav": "Indiana",
          "num": -33.7
        },
        "projTotal": 61.7,
        "homeRiser": 0,
        "awayRiser": 0,
        "pick": {
          "side": "North Texas",
          "num": 40.5
        },
        "totalLean": {
          "dir": "OVER",
          "num": 55.5
        },
        "off": false,
        "featured": true
      },
      {
        "away": "Liberty",
        "home": "James Madison",
        "neutral": 0,
        "commence": "2026-09-05T16:00:00.000Z",
        "conf": "Sun Belt",
        "marketSpread": {
          "fav": "James Madison",
          "num": -6.5
        },
        "marketTotal": 52.5,
        "projSpread": {
          "fav": "James Madison",
          "num": -12.8
        },
        "projTotal": 54.3,
        "homeRiser": 0,
        "awayRiser": 4,
        "pick": {
          "side": "James Madison",
          "num": -6.5
        },
        "totalLean": null,
        "off": false,
        "featured": true
      },
      {
        "away": "Ohio",
        "home": "Nebraska",
        "neutral": 0,
        "commence": "2026-09-05T16:00:00.000Z",
        "conf": "Big Ten",
        "marketSpread": {
          "fav": "Nebraska",
          "num": -23.5
        },
        "marketTotal": 47.5,
        "projSpread": {
          "fav": "Nebraska",
          "num": -16.9
        },
        "projTotal": 49.7,
        "homeRiser": 26,
        "awayRiser": 0,
        "pick": {
          "side": "Ohio",
          "num": 23.5
        },
        "totalLean": {
          "dir": "OVER",
          "num": 47.5
        },
        "off": false,
        "featured": false
      },
      {
        "away": "Oregon State",
        "home": "Houston",
        "neutral": 0,
        "commence": "2026-09-05T16:00:00.000Z",
        "conf": "Big 12",
        "marketSpread": {
          "fav": "Houston",
          "num": -20.5
        },
        "marketTotal": 51.0,
        "projSpread": {
          "fav": "Houston",
          "num": -17.6
        },
        "projTotal": 50.6,
        "homeRiser": 11,
        "awayRiser": 25,
        "pick": {
          "side": "Oregon State",
          "num": 20.5
        },
        "totalLean": null,
        "off": false,
        "featured": false
      },
      {
        "away": "Coastal Carolina",
        "home": "West Virginia",
        "neutral": 0,
        "commence": "2026-09-05T16:00:00.000Z",
        "conf": "Big 12",
        "marketSpread": {
          "fav": "West Virginia",
          "num": -21.5
        },
        "marketTotal": 56.5,
        "projSpread": {
          "fav": "West Virginia",
          "num": -13.6
        },
        "projTotal": 55.5,
        "homeRiser": 15,
        "awayRiser": 0,
        "pick": {
          "side": "Coastal Carolina",
          "num": 21.5
        },
        "totalLean": null,
        "off": false,
        "featured": false
      },
      {
        "away": "Ball State",
        "home": "Ohio State",
        "neutral": 0,
        "commence": "2026-09-05T16:30:00.000Z",
        "conf": "Big Ten",
        "marketSpread": {
          "fav": "Ohio State",
          "num": -50.5
        },
        "marketTotal": 56.5,
        "projSpread": {
          "fav": "Ohio State",
          "num": -50.0
        },
        "projTotal": 43.3,
        "homeRiser": 1,
        "awayRiser": 1,
        "pick": {
          "side": "Ball State",
          "num": 50.5
        },
        "totalLean": {
          "dir": "UNDER",
          "num": 56.5
        },
        "off": false,
        "featured": true
      },
      {
        "away": "Miami (OH)",
        "home": "Pittsburgh",
        "neutral": 0,
        "commence": "2026-09-05T16:30:00.000Z",
        "conf": "ACC",
        "marketSpread": {
          "fav": "Pittsburgh",
          "num": -16.5
        },
        "marketTotal": 49.5,
        "projSpread": {
          "fav": "Pittsburgh",
          "num": -13.3
        },
        "projTotal": 51.6,
        "homeRiser": 0,
        "awayRiser": 0,
        "pick": {
          "side": "Miami (OH)",
          "num": 16.5
        },
        "totalLean": {
          "dir": "OVER",
          "num": 49.5
        },
        "off": false,
        "featured": false
      },
      {
        "away": "Kent State",
        "home": "South Carolina",
        "neutral": 0,
        "commence": "2026-09-05T16:45:00.000Z",
        "conf": "SEC",
        "marketSpread": {
          "fav": "South Carolina",
          "num": -36.5
        },
        "marketTotal": 53.5,
        "projSpread": {
          "fav": "South Carolina",
          "num": -32.4
        },
        "projTotal": 50.6,
        "homeRiser": 20,
        "awayRiser": 0,
        "pick": {
          "side": "Kent State",
          "num": 36.5
        },
        "totalLean": {
          "dir": "UNDER",
          "num": 53.5
        },
        "off": false,
        "featured": false
      },
      {
        "away": "Boise State",
        "home": "Oregon",
        "neutral": 0,
        "commence": "2026-09-05T19:30:00.000Z",
        "conf": "Big Ten",
        "marketSpread": {
          "fav": "Oregon",
          "num": -24.5
        },
        "marketTotal": 52.0,
        "projSpread": {
          "fav": "Oregon",
          "num": -24.7
        },
        "projTotal": 53.3,
        "homeRiser": 1,
        "awayRiser": 0,
        "pick": {
          "side": "Oregon",
          "num": -24.5
        },
        "totalLean": null,
        "off": false,
        "featured": true
      },
      {
        "away": "Texas State",
        "home": "Texas",
        "neutral": 0,
        "commence": "2026-09-05T19:30:00.000Z",
        "conf": "SEC",
        "marketSpread": {
          "fav": "Texas",
          "num": -30.5
        },
        "marketTotal": 60.2,
        "projSpread": {
          "fav": "Texas",
          "num": -23.4
        },
        "projTotal": 58.6,
        "homeRiser": 8,
        "awayRiser": 0,
        "pick": {
          "side": "Texas State",
          "num": 30.5
        },
        "totalLean": null,
        "off": false,
        "featured": true
      },
      {
        "away": "Marshall",
        "home": "Penn State",
        "neutral": 0,
        "commence": "2026-09-05T19:30:00.000Z",
        "conf": "Big Ten",
        "marketSpread": {
          "fav": "Penn State",
          "num": -24.5
        },
        "marketTotal": 54.5,
        "projSpread": {
          "fav": "Penn State",
          "num": -24.6
        },
        "projTotal": 56.2,
        "homeRiser": 0,
        "awayRiser": 0,
        "pick": {
          "side": "Penn State",
          "num": -24.5
        },
        "totalLean": null,
        "off": false,
        "featured": true
      },
      {
        "away": "Baylor",
        "home": "Auburn",
        "neutral": 1,
        "commence": "2026-09-05T19:30:00.000Z",
        "conf": "SEC",
        "marketSpread": {
          "fav": "Auburn",
          "num": -7.0
        },
        "marketTotal": 59.5,
        "projSpread": {
          "fav": "Auburn",
          "num": -6.7
        },
        "projTotal": 54.5,
        "homeRiser": 14,
        "awayRiser": 13,
        "pick": {
          "side": "Baylor",
          "num": 7.0
        },
        "totalLean": {
          "dir": "UNDER",
          "num": 59.5
        },
        "off": false,
        "featured": false
      },
      {
        "away": "Tulane",
        "home": "Duke",
        "neutral": 0,
        "commence": "2026-09-05T19:30:00.000Z",
        "conf": "ACC",
        "marketSpread": {
          "fav": "Duke",
          "num": -9.5
        },
        "marketTotal": 51.0,
        "projSpread": {
          "fav": "Duke",
          "num": -10.2
        },
        "projTotal": 57.4,
        "homeRiser": 1,
        "awayRiser": 0,
        "pick": {
          "side": "Duke",
          "num": -9.5
        },
        "totalLean": {
          "dir": "OVER",
          "num": 51.0
        },
        "off": false,
        "featured": false
      },
      {
        "away": "Boston College",
        "home": "Cincinnati",
        "neutral": 0,
        "commence": "2026-09-05T19:30:00.000Z",
        "conf": "Big 12",
        "marketSpread": {
          "fav": "Cincinnati",
          "num": -7.5
        },
        "marketTotal": 51.5,
        "projSpread": {
          "fav": "Cincinnati",
          "num": -10.2
        },
        "projTotal": 55.3,
        "homeRiser": 4,
        "awayRiser": 19,
        "pick": {
          "side": "Cincinnati",
          "num": -7.5
        },
        "totalLean": {
          "dir": "OVER",
          "num": 51.5
        },
        "off": false,
        "featured": false
      },
      {
        "away": "Oklahoma State",
        "home": "Tulsa",
        "neutral": 0,
        "commence": "2026-09-05T19:45:00.000Z",
        "conf": "American Athletic",
        "marketSpread": {
          "fav": "Oklahoma State",
          "num": -14.0
        },
        "marketTotal": 60.5,
        "projSpread": {
          "fav": "Oklahoma State",
          "num": -4.8
        },
        "projTotal": 51.0,
        "homeRiser": 26,
        "awayRiser": 63,
        "pick": {
          "side": "Tulsa",
          "num": 14.0
        },
        "totalLean": {
          "dir": "UNDER",
          "num": 60.5
        },
        "off": false,
        "featured": false
      },
      {
        "away": "Northern Illinois",
        "home": "Iowa",
        "neutral": 0,
        "commence": "2026-09-05T20:15:00.000Z",
        "conf": "Big Ten",
        "marketSpread": {
          "fav": "Iowa",
          "num": -31.8
        },
        "marketTotal": 45.5,
        "projSpread": {
          "fav": "Iowa",
          "num": -32.7
        },
        "projTotal": 44.8,
        "homeRiser": 0,
        "awayRiser": 0,
        "pick": {
          "side": "Iowa",
          "num": -31.8
        },
        "totalLean": null,
        "off": false,
        "featured": true
      },
      {
        "away": "Wyoming",
        "home": "Colorado State",
        "neutral": 0,
        "commence": "2026-09-05T22:00:00.000Z",
        "conf": "Mountain West",
        "marketSpread": {
          "fav": "Colorado State",
          "num": -3.5
        },
        "marketTotal": 48.0,
        "projSpread": {
          "fav": "Colorado State",
          "num": -2.5
        },
        "projTotal": 44.4,
        "homeRiser": 11,
        "awayRiser": 9,
        "pick": {
          "side": "Wyoming",
          "num": 3.5
        },
        "totalLean": {
          "dir": "UNDER",
          "num": 48.0
        },
        "off": false,
        "featured": false
      },
      {
        "away": "Florida International",
        "home": "South Florida",
        "neutral": 0,
        "commence": "2026-09-05T23:00:00.000Z",
        "conf": "American Athletic",
        "marketSpread": {
          "fav": "South Florida",
          "num": -13.5
        },
        "marketTotal": 54.5,
        "projSpread": {
          "fav": "South Florida",
          "num": -17.9
        },
        "projTotal": 60.1,
        "homeRiser": 0,
        "awayRiser": 0,
        "pick": {
          "side": "South Florida",
          "num": -13.5
        },
        "totalLean": {
          "dir": "OVER",
          "num": 54.5
        },
        "off": false,
        "featured": true
      },
      {
        "away": "Missouri State",
        "home": "Texas A&M",
        "neutral": 0,
        "commence": "2026-09-05T23:00:00.000Z",
        "conf": "SEC",
        "marketSpread": {
          "fav": "Texas A&M",
          "num": -41.0
        },
        "marketTotal": 52.5,
        "projSpread": {
          "fav": "Texas A&M",
          "num": -36.5
        },
        "projTotal": 54.7,
        "homeRiser": 1,
        "awayRiser": 0,
        "pick": {
          "side": "Missouri State",
          "num": 41.0
        },
        "totalLean": {
          "dir": "OVER",
          "num": 52.5
        },
        "off": false,
        "featured": true
      },
      {
        "away": "Arkansas State",
        "home": "Memphis",
        "neutral": 0,
        "commence": "2026-09-05T23:00:00.000Z",
        "conf": "American Athletic",
        "marketSpread": {
          "fav": "Memphis",
          "num": -8.5
        },
        "marketTotal": 55.5,
        "projSpread": {
          "fav": "Memphis",
          "num": -15.2
        },
        "projTotal": 53.4,
        "homeRiser": 0,
        "awayRiser": 0,
        "pick": {
          "side": "Memphis",
          "num": -8.5
        },
        "totalLean": {
          "dir": "UNDER",
          "num": 55.5
        },
        "off": false,
        "featured": false
      },
      {
        "away": "Sam Houston",
        "home": "Troy",
        "neutral": 0,
        "commence": "2026-09-05T23:00:00.000Z",
        "conf": "Sun Belt",
        "marketSpread": {
          "fav": "Troy",
          "num": -16.5
        },
        "marketTotal": 53.5,
        "projSpread": {
          "fav": "Troy",
          "num": -19.8
        },
        "projTotal": 51.2,
        "homeRiser": 0,
        "awayRiser": 1,
        "pick": {
          "side": "Troy",
          "num": -16.5
        },
        "totalLean": {
          "dir": "UNDER",
          "num": 53.5
        },
        "off": false,
        "featured": false
      },
      {
        "away": "Clemson",
        "home": "LSU",
        "neutral": 0,
        "commence": "2026-09-05T23:30:00.000Z",
        "conf": "SEC",
        "marketSpread": {
          "fav": "LSU",
          "num": -10.5
        },
        "marketTotal": 51.2,
        "projSpread": {
          "fav": "LSU",
          "num": -8.2
        },
        "projTotal": 44.8,
        "homeRiser": 20,
        "awayRiser": 8,
        "pick": {
          "side": "Clemson",
          "num": 10.5
        },
        "totalLean": {
          "dir": "UNDER",
          "num": 51.2
        },
        "off": false,
        "featured": false
      },
      {
        "away": "Western Michigan",
        "home": "Michigan",
        "neutral": 0,
        "commence": "2026-09-05T23:30:00.000Z",
        "conf": "Big Ten",
        "marketSpread": {
          "fav": "Michigan",
          "num": -27.5
        },
        "marketTotal": 47.5,
        "projSpread": {
          "fav": "Michigan",
          "num": -21.6
        },
        "projTotal": 45.0,
        "homeRiser": 8,
        "awayRiser": 0,
        "pick": {
          "side": "Western Michigan",
          "num": 27.5
        },
        "totalLean": {
          "dir": "UNDER",
          "num": 47.5
        },
        "off": false,
        "featured": false
      },
      {
        "away": "UL Monroe",
        "home": "Mississippi State",
        "neutral": 0,
        "commence": "2026-09-05T23:30:00.000Z",
        "conf": "SEC",
        "marketSpread": {
          "fav": "Mississippi State",
          "num": -28.5
        },
        "marketTotal": 55.5,
        "projSpread": {
          "fav": "Mississippi State",
          "num": -30.3
        },
        "projTotal": 55.1,
        "homeRiser": 18,
        "awayRiser": 0,
        "pick": {
          "side": "Mississippi State",
          "num": -28.5
        },
        "totalLean": null,
        "off": false,
        "featured": false
      },
      {
        "away": "Florida Atlantic",
        "home": "Florida",
        "neutral": 0,
        "commence": "2026-09-05T23:45:00.000Z",
        "conf": "SEC",
        "marketSpread": {
          "fav": "Florida",
          "num": -26.5
        },
        "marketTotal": 59.5,
        "projSpread": {
          "fav": "Florida",
          "num": -22.2
        },
        "projTotal": 54.8,
        "homeRiser": 31,
        "awayRiser": 20,
        "pick": {
          "side": "Florida Atlantic",
          "num": 26.5
        },
        "totalLean": {
          "dir": "UNDER",
          "num": 59.5
        },
        "off": false,
        "featured": false
      },
      {
        "away": "UNLV",
        "home": "Hawai'i",
        "neutral": 0,
        "commence": "2026-09-06T02:00:00.000Z",
        "conf": "Mountain West",
        "marketSpread": null,
        "marketTotal": null,
        "projSpread": {
          "fav": "UNLV",
          "num": -2.1
        },
        "projTotal": 57.9,
        "homeRiser": 0,
        "awayRiser": 0,
        "pick": null,
        "totalLean": null,
        "off": false,
        "featured": false
      },
      {
        "away": "Central Michigan",
        "home": "New Mexico",
        "neutral": 0,
        "commence": "2026-09-06T02:00:00.000Z",
        "conf": "Mountain West",
        "marketSpread": {
          "fav": "New Mexico",
          "num": -11.5
        },
        "marketTotal": 47.5,
        "projSpread": {
          "fav": "New Mexico",
          "num": -16.1
        },
        "projTotal": 47.5,
        "homeRiser": 2,
        "awayRiser": 0,
        "pick": {
          "side": "New Mexico",
          "num": -11.5
        },
        "totalLean": null,
        "off": false,
        "featured": false
      },
      {
        "away": "UCLA",
        "home": "California",
        "neutral": 0,
        "commence": "2026-09-06T02:30:00.000Z",
        "conf": "ACC",
        "marketSpread": {
          "fav": "UCLA",
          "num": -1.5
        },
        "marketTotal": 53.5,
        "projSpread": {
          "fav": "California",
          "num": -2.5
        },
        "projTotal": 52.6,
        "homeRiser": 21,
        "awayRiser": 33,
        "pick": {
          "side": "California",
          "num": 1.5
        },
        "totalLean": null,
        "off": true,
        "featured": false
      },
      {
        "away": "Western Kentucky",
        "home": "Nevada",
        "neutral": 0,
        "commence": "2026-09-06T02:30:00.000Z",
        "conf": "Mountain West",
        "marketSpread": {
          "fav": "Western Kentucky",
          "num": -2.5
        },
        "marketTotal": 52.5,
        "projSpread": {
          "fav": "Western Kentucky",
          "num": -2.5
        },
        "projTotal": 49.2,
        "homeRiser": 9,
        "awayRiser": 0,
        "pick": {
          "side": "Western Kentucky",
          "num": -2.5
        },
        "totalLean": {
          "dir": "UNDER",
          "num": 52.5
        },
        "off": false,
        "featured": false
      },
      {
        "away": "Washington State",
        "home": "Washington",
        "neutral": 0,
        "commence": "2026-09-06T20:00:00.000Z",
        "conf": "Big Ten",
        "marketSpread": {
          "fav": "Washington",
          "num": -23.5
        },
        "marketTotal": 50.5,
        "projSpread": {
          "fav": "Washington",
          "num": -19.0
        },
        "projTotal": 47.9,
        "homeRiser": 2,
        "awayRiser": 0,
        "pick": {
          "side": "Washington State",
          "num": 23.5
        },
        "totalLean": {
          "dir": "UNDER",
          "num": 50.5
        },
        "off": false,
        "featured": true
      },
      {
        "away": "Louisville",
        "home": "Ole Miss",
        "neutral": 1,
        "commence": "2026-09-06T23:30:00.000Z",
        "conf": "SEC",
        "marketSpread": {
          "fav": "Ole Miss",
          "num": -6.5
        },
        "marketTotal": 55.5,
        "projSpread": {
          "fav": "Ole Miss",
          "num": -5.8
        },
        "projTotal": 54.1,
        "homeRiser": 0,
        "awayRiser": 0,
        "pick": {
          "side": "Louisville",
          "num": 6.5
        },
        "totalLean": null,
        "off": false,
        "featured": true
      },
      {
        "away": "Wisconsin",
        "home": "Notre Dame",
        "neutral": 1,
        "commence": "2026-09-06T23:30:00.000Z",
        "conf": "FBS Independents",
        "marketSpread": {
          "fav": "Notre Dame",
          "num": -20.5
        },
        "marketTotal": 47.5,
        "projSpread": {
          "fav": "Notre Dame",
          "num": -22.5
        },
        "projTotal": 47.5,
        "homeRiser": 0,
        "awayRiser": 15,
        "pick": {
          "side": "Notre Dame",
          "num": -20.5
        },
        "totalLean": null,
        "off": false,
        "featured": true
      },
      {
        "away": "SMU",
        "home": "Florida State",
        "neutral": 0,
        "commence": "2026-09-07T23:30:00.000Z",
        "conf": "ACC",
        "marketSpread": {
          "fav": "SMU",
          "num": -2.2
        },
        "marketTotal": 53.0,
        "projSpread": {
          "fav": "SMU",
          "num": -1.4
        },
        "projTotal": 52.6,
        "homeRiser": 14,
        "awayRiser": 0,
        "pick": {
          "side": "Florida State",
          "num": 2.2
        },
        "totalLean": null,
        "off": false,
        "featured": true
      }
    ],
    "upsets": [
      {
        "dog": "California",
        "matchup": "vs UCLA",
        "spread": "+1.5",
        "modelPct": 56,
        "marketPct": 47,
        "byPoints": 2.5
      }
    ]
  }
} as const;
