// AUTO-GENERATED by cfb_export.py -- do not edit by hand.
// Real, out-of-sample numbers from the CFB power rating over data/cfb.db.
export type NcaafTeam = { rank: number; team: string; conf: string; rating: number };
export type NcaafConf = { conf: string; avgRating: number; teams: number };
export type NcaafKeyNum = { margin: number; pct: number; nfl: number };
export type NcaafCardGame = { away: string; home: string; neutral: number; marketSpread: { fav: string; num: number } | null; marketTotal: number | null; projSpread: { fav: string; num: number }; projTotal: number; totalLean: { dir: string; num: number } | null; off: boolean };
export type NcaafUpset = { dog: string; matchup: string; spread: string; modelPct: number; marketPct: number; byPoints: number };
export const NCAAF_MODEL = {
  "season": 2025,
  "seasons": "2020-2025",
  "hfa": 3.2,
  "teamsRated": 136,
  "top": [
    {
      "rank": 1,
      "team": "Indiana",
      "conf": "Big Ten",
      "rating": 20.3
    },
    {
      "rank": 2,
      "team": "Ohio State",
      "conf": "Big Ten",
      "rating": 20.2
    },
    {
      "rank": 3,
      "team": "Notre Dame",
      "conf": "FBS Independents",
      "rating": 17.7
    },
    {
      "rank": 4,
      "team": "Oregon",
      "conf": "Big Ten",
      "rating": 16.5
    },
    {
      "rank": 5,
      "team": "Texas Tech",
      "conf": "Big 12",
      "rating": 16.0
    },
    {
      "rank": 6,
      "team": "Miami",
      "conf": "ACC",
      "rating": 15.8
    },
    {
      "rank": 7,
      "team": "Georgia",
      "conf": "SEC",
      "rating": 13.7
    },
    {
      "rank": 8,
      "team": "Utah",
      "conf": "Big 12",
      "rating": 13.4
    },
    {
      "rank": 9,
      "team": "Ole Miss",
      "conf": "SEC",
      "rating": 12.7
    },
    {
      "rank": 10,
      "team": "Texas A&M",
      "conf": "SEC",
      "rating": 11.4
    },
    {
      "rank": 11,
      "team": "Iowa",
      "conf": "Big Ten",
      "rating": 10.6
    },
    {
      "rank": 12,
      "team": "Vanderbilt",
      "conf": "SEC",
      "rating": 10.3
    },
    {
      "rank": 13,
      "team": "James Madison",
      "conf": "Sun Belt",
      "rating": 10.3
    },
    {
      "rank": 14,
      "team": "BYU",
      "conf": "Big 12",
      "rating": 10.3
    },
    {
      "rank": 15,
      "team": "USC",
      "conf": "Big Ten",
      "rating": 10.2
    },
    {
      "rank": 16,
      "team": "Penn State",
      "conf": "Big Ten",
      "rating": 10.1
    },
    {
      "rank": 17,
      "team": "Texas",
      "conf": "SEC",
      "rating": 10.1
    },
    {
      "rank": 18,
      "team": "Alabama",
      "conf": "SEC",
      "rating": 9.9
    },
    {
      "rank": 19,
      "team": "SMU",
      "conf": "ACC",
      "rating": 9.7
    },
    {
      "rank": 20,
      "team": "Washington",
      "conf": "Big Ten",
      "rating": 9.6
    },
    {
      "rank": 21,
      "team": "Oklahoma",
      "conf": "SEC",
      "rating": 8.1
    },
    {
      "rank": 22,
      "team": "South Florida",
      "conf": "American Athletic",
      "rating": 7.8
    },
    {
      "rank": 23,
      "team": "Louisville",
      "conf": "ACC",
      "rating": 7.3
    },
    {
      "rank": 24,
      "team": "North Texas",
      "conf": "American Athletic",
      "rating": 7.2
    },
    {
      "rank": 25,
      "team": "Tennessee",
      "conf": "SEC",
      "rating": 7.0
    }
  ],
  "validation": {
    "games": 2822,
    "ourSU": 71.0,
    "eloSU": 70.6,
    "homeSU": 56.5,
    "ourRMSE": 16.43,
    "eloRMSE": 16.15
  },
  "ats": {
    "bets": 2306,
    "wins": 1126,
    "losses": 1157,
    "atsPct": 49.3,
    "breakeven": 52.38
  },
  "context": {
    "hfa": 3.2,
    "conferences": [
      {
        "conf": "SEC",
        "avgRating": 6.3,
        "teams": 16
      },
      {
        "conf": "Big Ten",
        "avgRating": 5.4,
        "teams": 18
      },
      {
        "conf": "Big 12",
        "avgRating": 3.3,
        "teams": 16
      },
      {
        "conf": "ACC",
        "avgRating": 1.7,
        "teams": 17
      },
      {
        "conf": "American Athletic",
        "avgRating": -2.6,
        "teams": 14
      },
      {
        "conf": "Mountain West",
        "avgRating": -3.2,
        "teams": 12
      },
      {
        "conf": "Sun Belt",
        "avgRating": -3.7,
        "teams": 14
      },
      {
        "conf": "Conference USA",
        "avgRating": -6.2,
        "teams": 12
      },
      {
        "conf": "Mid-American",
        "avgRating": -6.8,
        "teams": 13
      }
    ]
  },
  "value": {
    "games": 4478,
    "keyNumbers": [
      {
        "margin": 3,
        "pct": 10.6,
        "nfl": 15.0
      },
      {
        "margin": 7,
        "pct": 8.6,
        "nfl": 9.1
      },
      {
        "margin": 10,
        "pct": 4.6,
        "nfl": 5.8
      },
      {
        "margin": 14,
        "pct": 4.4,
        "nfl": 4.9
      }
    ],
    "bookShop": {
      "games": 3935,
      "avgRange": 0.78,
      "pctGap1": 30
    }
  },
  "card": {
    "season": 2026,
    "week": 1,
    "games": [
      {
        "away": "Louisville",
        "home": "Ole Miss",
        "neutral": 1,
        "marketSpread": {
          "fav": "Ole Miss",
          "num": -6.5
        },
        "marketTotal": 55.5,
        "projSpread": {
          "fav": "Ole Miss",
          "num": -3.2
        },
        "projTotal": 54.1,
        "totalLean": null,
        "off": false
      },
      {
        "away": "North Texas",
        "home": "Indiana",
        "neutral": 0,
        "marketSpread": {
          "fav": "Indiana",
          "num": -40.5
        },
        "marketTotal": 55.5,
        "projSpread": {
          "fav": "Indiana",
          "num": -11.1
        },
        "projTotal": 61.7,
        "totalLean": {
          "dir": "OVER",
          "num": 55.5
        },
        "off": false
      },
      {
        "away": "Clemson",
        "home": "LSU",
        "neutral": 0,
        "marketSpread": {
          "fav": "LSU",
          "num": -10.5
        },
        "marketTotal": 51.0,
        "projSpread": {
          "fav": "LSU",
          "num": -2.7
        },
        "projTotal": 44.8,
        "totalLean": {
          "dir": "UNDER",
          "num": 51.0
        },
        "off": false
      },
      {
        "away": "Washington State",
        "home": "Washington",
        "neutral": 0,
        "marketSpread": {
          "fav": "Washington",
          "num": -22.8
        },
        "marketTotal": 50.5,
        "projSpread": {
          "fav": "Washington",
          "num": -6.2
        },
        "projTotal": 47.9,
        "totalLean": {
          "dir": "UNDER",
          "num": 50.5
        },
        "off": false
      },
      {
        "away": "Boise State",
        "home": "Oregon",
        "neutral": 0,
        "marketSpread": {
          "fav": "Oregon",
          "num": -24.5
        },
        "marketTotal": 52.5,
        "projSpread": {
          "fav": "Oregon",
          "num": -10.6
        },
        "projTotal": 53.3,
        "totalLean": null,
        "off": false
      },
      {
        "away": "East Carolina",
        "home": "Alabama",
        "neutral": 0,
        "marketSpread": {
          "fav": "Alabama",
          "num": -28.5
        },
        "marketTotal": 54.0,
        "projSpread": {
          "fav": "Alabama",
          "num": -6.8
        },
        "projTotal": 50.4,
        "totalLean": {
          "dir": "UNDER",
          "num": 54.0
        },
        "off": false
      },
      {
        "away": "Tulane",
        "home": "Duke",
        "neutral": 0,
        "marketSpread": {
          "fav": "Duke",
          "num": -9.5
        },
        "marketTotal": 52.0,
        "projSpread": {
          "fav": "Duke",
          "num": -3.0
        },
        "projTotal": 57.4,
        "totalLean": {
          "dir": "OVER",
          "num": 52.0
        },
        "off": false
      },
      {
        "away": "Memphis",
        "home": "UNLV",
        "neutral": 0,
        "marketSpread": {
          "fav": "UNLV",
          "num": -5.5
        },
        "marketTotal": 57.5,
        "projSpread": {
          "fav": "UNLV",
          "num": -2.9
        },
        "projTotal": 58.1,
        "totalLean": null,
        "off": false
      },
      {
        "away": "NC State",
        "home": "Virginia",
        "neutral": 0,
        "marketSpread": {
          "fav": "Virginia",
          "num": -5.5
        },
        "marketTotal": 53.5,
        "projSpread": {
          "fav": "Virginia",
          "num": -4.7
        },
        "projTotal": 52.6,
        "totalLean": null,
        "off": false
      },
      {
        "away": "Texas State",
        "home": "Texas",
        "neutral": 0,
        "marketSpread": {
          "fav": "Texas",
          "num": -30.5
        },
        "marketTotal": 60.0,
        "projSpread": {
          "fav": "Texas",
          "num": -7.9
        },
        "projTotal": 58.6,
        "totalLean": null,
        "off": false
      },
      {
        "away": "SMU",
        "home": "Florida State",
        "neutral": 0,
        "marketSpread": {
          "fav": "SMU",
          "num": -2.5
        },
        "marketTotal": 53.0,
        "projSpread": {
          "fav": "SMU",
          "num": -1.5
        },
        "projTotal": 52.6,
        "totalLean": null,
        "off": false
      },
      {
        "away": "Western Michigan",
        "home": "Michigan",
        "neutral": 0,
        "marketSpread": {
          "fav": "Michigan",
          "num": -27.5
        },
        "marketTotal": 48.0,
        "projSpread": {
          "fav": "Michigan",
          "num": -7.2
        },
        "projTotal": 45.0,
        "totalLean": {
          "dir": "UNDER",
          "num": 48.0
        },
        "off": false
      },
      {
        "away": "Ohio",
        "home": "Nebraska",
        "neutral": 0,
        "marketSpread": {
          "fav": "Nebraska",
          "num": -24.0
        },
        "marketTotal": 47.5,
        "projSpread": {
          "fav": "Nebraska",
          "num": -2.3
        },
        "projTotal": 49.7,
        "totalLean": {
          "dir": "OVER",
          "num": 47.5
        },
        "off": false
      },
      {
        "away": "Baylor",
        "home": "Auburn",
        "neutral": 1,
        "marketSpread": {
          "fav": "Auburn",
          "num": -7.0
        },
        "marketTotal": 59.5,
        "projSpread": {
          "fav": "Auburn",
          "num": -2.5
        },
        "projTotal": 54.5,
        "totalLean": {
          "dir": "UNDER",
          "num": 59.5
        },
        "off": false
      },
      {
        "away": "Fresno State",
        "home": "USC",
        "neutral": 0,
        "marketSpread": {
          "fav": "USC",
          "num": -23.0
        },
        "marketTotal": 51.5,
        "projSpread": {
          "fav": "USC",
          "num": -9.7
        },
        "projTotal": 51.1,
        "totalLean": null,
        "off": false
      },
      {
        "away": "Wisconsin",
        "home": "Notre Dame",
        "neutral": 1,
        "marketSpread": {
          "fav": "Notre Dame",
          "num": -20.5
        },
        "marketTotal": 47.5,
        "projSpread": {
          "fav": "Notre Dame",
          "num": -11.1
        },
        "projTotal": 47.5,
        "totalLean": null,
        "off": false
      }
    ],
    "upsets": [
      {
        "dog": "Sacramento State",
        "matchup": "at Eastern Michigan",
        "spread": "+9.5",
        "modelPct": 54,
        "marketPct": 30,
        "byPoints": 1.7
      },
      {
        "dog": "California",
        "matchup": "vs UCLA",
        "spread": "+1.0",
        "modelPct": 58,
        "marketPct": 48,
        "byPoints": 3.4
      }
    ]
  }
} as const;
